### ISSUE TITLE
Chain multiple events

### ISSUE THREAD

**Issue by atellier** [cronicle-edge/cronicle-edge#10]
Hi!

First of all, thanks a lot for this great fork! Love the new additions.

I was wondering if it would be possible to chain multiple events. Like Job A triggers Job B & C (multiple box in A?)  

A potentially even more flexible / natural solution would be to declare that linkage in B & C as a dependency on event A, so that they run when A completes (error / succession could be chosen). 

Thanks!

**Comment by mikeTWC1984** [comment]
Thanks :)
I think I opened similar issue on original cronicle sometime ago. If using edge fork you can achieve that using workflow plugin, but what you are asking also sounds reasonable, I'll check when I get a chance.

Regarding second part, I think it's essentially the same thing (chain vs dependency). Probably it make sense to have "event" as a trigger (along with cron expression). I'll keep it in in mind. Might wait till cornicle 2.0 (orchestra) though, jhuckaby promised some new options for chaining.

**Comment by atellier** [comment]
Hi,

Thanks for your comment. I am using now the Workflow and it indeed fulfills part of what i am trying to achieve. 

Speaking of Workflow, I am getting an error when using the workflow plugin: `"cannot read of undefined (reading 'title')`. This error only happens every time when I set a concurrency (like 16). If I use "sync", then the error does not happen.

Thank you,

**Comment by mikeTWC1984** [comment]
What version are you using? I think in older versions if you set concurrency > job count it will through this error. In recent releases it was fixed.

**Comment by atellier** [comment]
Hi, I am using 1.5.2. I will try to update and report back if new version still has issues. Thanks

**Comment by mikeTWC1984** [comment]
Ok, cool. Looking forward to hear for feedback. Workflow has bunch of edge cases, we keep improving it.

Btw, I added an option to generate "workflow api key" as a plugin option (you need to check "Workflow" check box on plugin options). This way you can create you own plugins like that or enhance shell plugin with such functionality (without hardcoding/managing api keys)

Here is example bash script

```bash
echo $BASE_URL
echo $WF_SIGNATURE

url="$BASE_URL/api/app/run_event?title=test&arg=123"

curl -s -H "x-wf-signature: $WF_SIGNATURE" -H "x-wf-id: $JOB_ID" $url
```
