### ISSUE TITLE
Performance history not properly fit

### ISSUE THREAD

**Issue by LukaszBrzyszkiewicz** [cronicle-edge/cronicle-edge#100]
When running Workflow plugin with many items and long parameters - graph is not fitting in window, because all space is taken by the legend.

![obraz](https://github.com/cronicle-edge/cronicle-edge/assets/88447452/1efef6fc-cc59-456b-8139-5a42b66781ed)

**Comment by mikeTWC1984** [comment]
What browser are you using? How many events? I tried WF with 25 events, it look OK

**Comment by dheise-rheinenergie-trading-com** [comment]
Same here. The performance graph is totally hidden:

![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/565c3e94-271a-4bd6-9fa2-4f7a3395c41d)

Workflow with 95 events.

**Comment by LukaszBrzyszkiewicz** [comment]
I'm using Firefox v124.0.2 - but I don't think that this is related to the browser.

**Comment by mikeTWC1984** [comment]
OK. Well I doubt visualizing 90+ data series is particularly, perhaps need to use some heat map.

But if you will keep those legends, it won't fit the screen in any case. Try to hide them using browsers console:
```js
$P().charts.perf.options.legend.display = false
$P().charts.perf.update()
```
Does it look any better? I guess not.

**Comment by dheise-rheinenergie-trading-com** [comment]
Looks better. I think a legend is not really neccessary. Showing the job name and the values while hovering the graph should be enough.

![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/2577b0e8-16f3-4191-90e9-a80499d14197)

**Comment by LukaszBrzyszkiewicz** [comment]
Yes - much better view

**Comment by mikeTWC1984** [comment]
OK, you can now toggle legend by clicking on "Performance History" title (as a quick-and-dirty solution). 
To my mind those time-series graphs with over 10 lines are not human readable anyway , need to think of some better chart type for those
