### ISSUE TITLE
Passing secrets through environment variables to a docker container

### ISSUE THREAD

**Issue by scls19fr** [cronicle-edge/cronicle-edge#102]
Hello,

I'm using Cronicle-Edge in a Docker container to run periodicaly new container from a Docker image (which should run a Python script which ingest data to a server).

My Python script uses environment variables to get secrets such as login(email)/password/host of server ...

I noticed that when creating Events with Plugin Docker, there is a field named "Secrets"
where it written

    Specify KEY=VALUE pairs to be mounted as env variables (to this job process)

I added my env variable like so

    MYSERVER_API_HOST=myserver-api:5000
    MYSERVER_API_USE_SSL=0
    MYSERVER_EMAIL=admin@domain.com
    MYSERVER_PASSWORD=password

Unfortunately my Python script doesn't get these environment variables.

I added to my Python script simply

    print(os.environ)

and saw

    environ({'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/cronicle/.local/bin', 'HOSTNAME': '3cd6de2c558e', 'BASE_URL': 'http://manager:3012', 'BASE_APP_URL': 'http://localhost:3012', 'JOB_ID': 'jluz7rodz0r', 'JOB_LOG': '/opt/cronicle/logs/jobs/jluz7rodz0r.log', 'JOB_NOW': '1713080280', 'JOB_TIMEOUT': '3600', 'JOB_CATCH_UP': '0', 'JOB_QUEUE_MAX': '1000', 'JOB_TIMEZONE': 'Europe/Paris', 'JOB_PLUGIN': 'dockerplug', 'JOB_THEME': 'default', 'JOB_SILENT': '0', 'JOB_CONCURRENT_ARG': '0', 'JOB_GRAPH_ICON': '', 'JOB_ARGS': '', 'JOB_CATEGORY': 'general', 'JOB_TARGET': 'allgrp', 'JOB_ALGO': 'random', 'JOB_MULTIPLEX': '0', 'JOB_STAGGER': '0', 'JOB_RETRIES': '0', 'JOB_RETRY_DELAY': '0', 'JOB_DETACHED': '0', 'JOB_QUEUE': '0', 'JOB_CHAIN': '', 'JOB_CHAIN_ERROR': '', 'JOB_NOTIFY_SUCCESS': '', 'JOB_NOTIFY_FAIL': '', 'JOB_WEB_HOOK': '', 'JOB_WEB_HOOK_START': '', 'JOB_WEB_HOOK_ERROR': '0', 'JOB_CPU_LIMIT': '0', 'JOB_CPU_SUSTAIN': '0', 'JOB_MEMORY_LIMIT': '0', 'JOB_MEMORY_SUSTAIN': '0', 'JOB_LOG_MAX_SIZE': '0', 'JOB_NOTES': '', 'JOB_SECRET_PREVIEW': 'MYSERVER_API_HOST|MYSERVER_API_USE_SSL|MYSERVER_EMAIL|MYSERVER_PASSWORD', 'JOB_ENCRYPTED': '1', 'JOB_TIME_START': '1713080280.887', 'JOB_HOSTNAME': 'manager', 'JOB_EVENT': 'eluyjqwcz01', 'JOB_EVENT_TITLE': 'test docker', 'JOB_PLUGIN_TITLE': 'Docker', 'JOB_CATEGORY_TITLE': 'General', 'JOB_NICE_TARGET': 'All Servers', 'JOB_IPC': '1', 'JOB_LAG': '1713080280886', 'JOB_STDIN': '0', 'JOB_LAST_EXIT_CODE': '1', 'JOB_COMMAND': 'node bin/docker-plugin.js', 'JOB_LOG_FILE': '/opt/cronicle/logs/jobs/jluz7rodz0r.log', 'DOCKER_HOST': '', 'IMAGE': 'ingest-data-ingest-service', 'ENTRYPOINT_PATH': '', 'PULL_IMAGE': '1', 'KEEP_CONTAINER': '0', 'LANG': 'C.UTF-8', 'GPG_KEY': '7169605F62C751356D054A26A821E680E5FA6305', 'PYTHON_VERSION': '3.12.3', 'PYTHON_PIP_VERSION': '24.0', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py', 'PYTHON_GET_PIP_SHA256': 'dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9', 'GROUP': 'cronicle', 'HOME': '/home/cronicle'})

So environment variables have `JOB_SECRET_PREVIEW` (which contains `'MYSERVER_API_HOST|MYSERVER_API_USE_SSL|MYSERVER_EMAIL|MYSERVER_PASSWORD'`) 

but it doesn't seems to have `MYSERVER_API_HOST`, `MYSERVER_API_USE_SSL`, ...

I added also in my Python script

    print(os.getuid()) # numeric uid
    print(pwd.getpwuid(os.getuid())) # full /etc/passwd info

to see if my script is running with the right user / group ie cronicle / cronicle and I saw

    1000
    pwd.struct_passwd(pw_name='cronicle', pw_passwd='x', pw_uid=1000, pw_gid=1099, pw_gecos='', pw_dir='/home/cronicle', pw_shell='/bin/ash')

My Dockerfile looks like

```
FROM python:alpine3.19

ARG USER=nonroot
ARG UID=1010
ARG GID=1010
ENV GROUP=${USER}

#RUN apk add --no-cache ...

# install some pip packages as root (not recommanded... but useful here to run with some Docker job schedulers)
#COPY requirements.txt .
#RUN pip install --no-cache -r requirements.txt

# Create a non-root user
RUN addgroup -g ${GID} ${GROUP} && \
    adduser -u ${UID} -G $GROUP -D -g "" ${USER}
# Add /home/${USER}/.local/bin
ENV PATH=${PATH}:/home/${USER}/.local/bin
# Change user to a non-root user
USER $USER

COPY requirements.txt .
RUN pip install --no-cache -r requirements.txt

COPY --chown=${USER}:${GROUP} --chmod=500 app.py /home/${USER}/app/app.py

WORKDIR /home/${USER}/app

ENTRYPOINT ["python", "app.py"]
```

I build my image with the following docker-compose.yml

```
services:
  ingest-service:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSERVER_API_HOST=${MYSERVER_API_HOST}
      - MYSERVER_API_USE_SSL=${MYSERVER_API_USE_SSL}
      - MYSERVER_EMAIL=${MYSERVER_EMAIL}
      - MYSERVER_PASSWORD=${MYSERVER_PASSWORD}
    networks:
      - myserver-docker_default

networks:
  myserver-docker_default:
    external: true
```

and the following command

    docker compose build --build-arg USER=cronicle --build-arg GROUP=cronicle --build-arg UID=1000 --build-arg GID=1099 --no-cache

Did I miss something or is it a bug?

I can't understand why my Python script can't get environment variable.

Any idea?

**Comment by mikeTWC1984** [comment]
Yeah, if you want to pass custom variable to docker container you need to add prefix DOCKER_. Same for ssh plugin, where you need add prefix SSH_. This will prevent leaking your local variables to external machines.

**Comment by scls19fr** [comment]
Thanks but that's a bit odd... because with such a solution you must modify your script to use environment variables starting with `DOCKER_`

I thouht that setting

```
DOCKER_MYSERVER_API_HOST=myserver-api:5000
DOCKER_MYSERVER_API_USE_SSL=0
DOCKER_MYSERVER_EMAIL=admin@domain.com
DOCKER_MYSERVER_PASSWORD=password
```

will made environment variable accessible inside scheduled container through


```
MYSERVER_API_HOST
MYSERVER_API_USE_SSL
MYSERVER_EMAIL
MYSERVER_PASSWORD
```

but that's not the case as they are accessible through

```
DOCKER_MYSERVER_API_HOST
DOCKER_MYSERVER_API_USE_SSL
DOCKER_MYSERVER_EMAIL
DOCKER_MYSERVER_PASSWORD
```
