### ISSUE TITLE
Passing network parameter to a docker container

### ISSUE THREAD

**Issue by scls19fr** [cronicle-edge/cronicle-edge#104]
Hello,

following #102 , I encoutered an other problem

My Python script raises

    Unexpected error while requesting http://myserver-api:5000/timeseries_data/campaign/20/: HTTPConnectionPool(host='myserver-api', port=5000): Max retries exceeded with url: /timeseries_data/campaign/20/?start_time=2024-04-15+09%3A07%3A18.035154%2B02%3A00&end_time=2024-04-15+10%3A07%3A18.035154%2B02%3A00&data_state=1&timeseries=TS0&timeseries=HUM0&timezone=UTC (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f95d4a0a690>: Failed to resolve 'myserver-api' ([Errno -2] Name does not resolve)"))
    Unexpected error while requesting http://myserver-api:5000/timeseries_data/campaign/20/: HTTPConnectionPool(host='myserver-api', port=5000): Max retries exceeded with url: /timeseries_data/campaign/20/?data_state=1 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f95d4a51a60>: Failed to resolve 'myserver-api' ([Errno -2] Name does not resolve)"))

I think my scheduled container doesn't run with same network parameter that `myserver-api` container.

So I need my scheduled container use a custom network (ie same network as the one being used by `myserver-api` container and also by cronicle-edge).

Unfortunately I don't see if / where I can set this.

Any idea ?

**Comment by mikeTWC1984** [comment]
It's not a part of the plugin yet, but definitely any docker cli option is addable to plugin. 
You can play around and add option you want here:
https://github.com/cronicle-edge/cronicle-edge/blob/65f57cdca4afbb913cf2f7c3725f23f3eb00dacf/bin/docker-plugin.js#L126

I guess for network you should use HostConfig property:
https://github.com/apocas/dockerode/issues/501

I don't really want to clog plugin with too many parameters, but I guess this one make sense, I'll likely add it on the next release

**Comment by mikeTWC1984** [comment]
This was added in recent releases closing

**Comment by scls19fr** [comment]
Thanks @mikeTWC1984
