### ISSUE TITLE
How to migrate storage engines?

### ISSUE THREAD

**Issue by kmorrisCAL** [cronicle-edge/cronicle-edge#105]
I've been running Cronicle for several months now using the local filesystem as the "storage engine".
I would like to migrate to SQLite.  I see the "backup schedule" button, but I would also like to retain the historical output/records and configuration changes.
Is there a recommended path to accomplish this goal?

Thank you!

**Comment by mikeTWC1984** [comment]
Yes, you can use standard migration tool. it's under bin/storage-migrate.js
If you use bundle then you need to add --tools flag to bundle it: ```./bundle --tools --sqlite```

Standard way is to add NewStorage property in you config.json, and then run storage-migrate.js without any parameter.
That property should look like this, you just change the filename parameter:
```json
{
    "engine": "SQL",
    "list_page_size": 50,
    "concurrency": 4,
    "log_event_types": { "get": 1, "put": 1, "head": 1,	"delete": 1, "expire_set": 1 },
    "SQL": {
        "client": "sqlite3",
        "table": "cronicle",
        "useNullAsDefault": true,
        "connection": {
            "filename": "cronicle.db"
        }
    }
}
```
I added some goodness for sqlite on the latest release (1.8.2, check release notes), so if you using it you can just dump you current storage into sqlite like this: 
```./dist/bin/storage-migrate.js --sqlite /path/to/dump.db ```
The latest version will also use sql transaction during setup and migration, it will be way much faster for sqlite than older versions.

**Comment by kmorrisCAL** [comment]
Thank you for the quick and informational/instructional response.  This worked beautifully!
