### ISSUE TITLE
Constants/Variables for reference in plugins

### ISSUE THREAD

**Issue by josephdadams** [cronicle-edge/cronicle-edge#108]
It would be great if we could have a section to define constants that we could then refer to inside plugin fields. So if I have to change an IP address or something, I just change it in the constants/variables section instead of in multiple instances/events.

**Comment by mikeTWC1984** [comment]
You can just add "Hidden" parameter to you plugin to achieve this. This is standard cronicle feature. Other option is to attach secret (which is basically env variable) to plugin (if you are on 1.8.0 or higher), it can also be done within category scope. Go to admin/secret, select scope and set KEY=VALUE pairs as needed.
