### ISSUE TITLE
docker image please support arm64 architecture

### ISSUE THREAD

**Issue by iferencz** [cronicle-edge/cronicle-edge#112]
I don't have an amd architecture server, thank you very much.

**Comment by mikeTWC1984** [comment]
The cronicle/edge image on dockerhub should support arm64,  did you try  it? I also have another image for raspberrypi / arm7  - cronicle/edge-pi

**Comment by iferencz** [comment]
> The cronicle/edge image on dockerhub should support arm64, did you try it? I also have another image for raspberrypi / arm7 - cronicle/edge-pi

I forgot about dockerhub, I directly used docker pull `ghcr.io/cronicle-edge/cronicle-edge:latest`, thank you!
