### ISSUE TITLE
show seconds in job detail view

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#115]
Hi Mike,

would it be possible to make it configurable to show the seconds for job start and job end on the details page? The used function get_nice_time from pixl-webapp supports a parameter for return the seconds. This would help me a lot for checking critical jobs which runs every minute.

Daniel

**Comment by mikeTWC1984** [comment]
Added on 1.9.4

**Comment by dheise-rheinenergie-trading-com** [comment]
Hey Mike. Thank you so much!
