### ISSUE TITLE
Missing parameter error for title when creating event via API

### ISSUE THREAD

**Issue by Aub-C** [cronicle-edge/cronicle-edge#117]
I'm encountering an issue when trying to create an event using the /api/app/create_event/v1 endpoint. Despite including the title parameter in the request body, I receive an error indicating that the title parameter is missing.

https://mycron.url.com/api/app/create_event/v1?api_key=************************************

```
{
    "event": {
        "title": "Ping Google",
        "enabled": 1,
        "params": {
            "method": "GET",
            "url": "http://google.com",
            "headers": "User-Agent: Cronicle/1.0",
            "timeout": "80"
        },
        "timing": {
            "hours": [ 21 ],
            "minutes": [ 20, 40 ]
        },
        "timezone": "America/New_York",
        "plugin": "urlplug",
        "category": "clwuqk9lvys",
        "web_hook": "slack_general",
        "web_hook_error": 1,
        "username": "aub"
    }
}
```

Error Response:
```
{
    "code": "api",
    "description": "Missing parameter: title"
}
```

Steps to Reproduce:
    * Send a POST request to /api/app/create_event/v1 with the provided request body.
    * Observe the error response indicating the missing title parameter.
    
Expected Behavior:
    * The event should be created successfully with the provided title parameter.

Environment:
    * Cronicle version: 1.9.4
    * API endpoint: /api/app/create_event/v1

**Comment by mikeTWC1984** [comment]
You shouldn't wrap event in {"event": ... }.  Only include this
{
        "title": "Ping Google",
        "enabled": 1,
        "params": {
            "method": "GET",
            "url": "http://google.com",
            "headers": "User-Agent: Cronicle/1.0",
            "timeout": "80"
        },
        "timing": {
            "hours": [ 21 ],
            "minutes": [ 20, 40 ]
        },
        "timezone": "America/New_York",
        "plugin": "urlplug",
        "category": "clwuqk9lvys",
        "web_hook": "slack_general",
        "web_hook_error": 1,
        "username": "aub"
    }

If it still doesn't work, open dev tools, open network tab, create event manually and follow same request

**Comment by Aub-C** [comment]
Working. Thank you!!
