### ISSUE TITLE
text editor for shell plugin doesn't show code anymore

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#119]
Today we upgraded our cluster from 1.7.8 to 1.9.4. Now we don't see our code anymore for all events which uses the shell plugin. The Code panel is only empty.

No error message or something else. We can run the events and the output is as aspected. So the code is still there. 

The dev console from my edge browser shows the following error if I edit a event:

```
codemirror.min.js:12  Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Ha (codemirror.min.js:12:9433)
    at new it (codemirror.min.js:12:13823)
    at it (codemirror.min.js:12:13545)
    at Function.ou [as fromTextArea] (codemirror.min.js:24:2201)
    at members.__construct.container.<computed>.setScriptEditor (combo.min.js:234:13699)
    at members.__construct.container.<computed>.refresh_plugin_params (combo.min.js:253:643)
    at members.__construct.container.<computed>.change_edit_plugin (combo.min.js:234:12950)
    at HTMLSelectElement.onchange (VM151 :1:6)
```

Cronicle is running without a docker container. My upgrade procedure was:
- download the current release as zip
- unpack zip
- stop running instance
- running ./bundle /opt/cronicle 
-start cronicle

my previous version of cronicle was already installed under /opt/cronicle

Daniel

**Comment by mikeTWC1984** [comment]
Just for sanity check, try to clean up browser cache. 
So since it coming from codemirror.js perhaps  some new version of it was installed. I'll check

**Comment by dheise-rheinenergie-trading-com** [comment]
cleaned up browser cache, used private tab, switched to chrome... no success. All 3 servers from my cluster have the same problem.

**Comment by dheise-rheinenergie-trading-com** [comment]
connecting directly over http/3012, https/3013 or connecting through my network load balancer makes also no difference.

**Comment by dheise-rheinenergie-trading-com** [comment]
the problematic code line in the source file node_modules/codemirror/lib/codemirror.js

![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/a1920834-7e62-4d0e-8ad3-a9cdee3e21b0)

**Comment by dheise-rheinenergie-trading-com** [comment]
mhmmm.... cronicle edge 1.7.8 used codemirror 5.6.15 and cronicle edge 1.9.4 uses codemirror 5.6.16. I changed the dependency for codemirror to 5.6.15 for cronicle 1.9.4 and bundled again. The problem is still there. Could it be a problem with the bundling itself?

**Comment by mikeTWC1984** [comment]
OK. Can you create some dummy job and see if it changes anything. Perhaps need to intit some objects in the storage or something like that. I think I've seen something similar a while ago, but cannot recall. I'll try to reproduce the error later today

**Comment by mikeTWC1984** [comment]
I tried to upgrade from 1.7.8 to 1.9.4 (by manual install), I wasn't able to reproduce. Can you attach here codemirror.js.min and combo.min.js  that you generated while bundling 1.9.4?

**Comment by mikeTWC1984** [comment]
One more thing to try. Go to edit mode on some event that has that issue, open browser console, then type this commands:

```javascript
// see if you can get script text box
el = document.getElementById("fe_ee_pp_script")
// then init editor, technically it should render text box with syntax highlighting, does it fail?
let editor = CodeMirror.fromTextArea(el)
```

**Comment by dheise-rheinenergie-trading-com** [comment]
the javascript works. I get a second textarea which shows my code:

![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/cc4ed9b4-d986-4ef7-a460-e663beaf4fe1)

**Comment by dheise-rheinenergie-trading-com** [comment]
js files attached:

[codemirror.min.js.txt](https://github.com/user-attachments/files/15574512/codemirror.min.js.txt)
[combo.min.js.txt](https://github.com/user-attachments/files/15574513/combo.min.js.txt)

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike,

I found the reason. Our shell plugin definition in the database was way to old. A couple of parameters where missing:

before:
![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/5a88dfee-1cb4-403e-87de-5f4540f03cc7)

after:
![image](https://github.com/cronicle-edge/cronicle-edge/assets/73586581/2a1c01e4-1793-4ba4-97ff-f5194917ba94)

after updating the plugin, I opened an event - the codebox is still empty. I only have to save the unchanged event again und reload the edit page and the code reappears. Now I have to update ~750 events.... 😣

**Comment by mikeTWC1984** [comment]
Hm, Ok. So perhaps the issue comes from "files" parameter since it also has code editor. I think that just the matter of adding extra null check., no need to do 750 updates.  I'll review

**Comment by mikeTWC1984** [comment]
Although based on stack trace you pasted issue comes from setScriptEditor (that renders main script). 

https://github.com/cronicle-edge/cronicle-edge/blob/main/htdocs/js/pages/Schedule.class.js#L2713

You were able to run  CodeMirror.fromTextArea , so probably when parameters added something get broken. At a glance looks like theme variable is null, probably codemirror doesnt like it. Try to follow setScriptEditor  in browser console, I guess one of the option is null or something.

**Comment by mikeTWC1984** [comment]
yeah, looks like this is it if I do this I just get empt box:

```js
let editor = CodeMirror.fromTextArea(el, {theme: null} )
```

so just add null check and assign default value, e.g.

theme: theme || 'default'
