### ISSUE TITLE
SSHX On Mac (base64 decode issue)

### ISSUE THREAD

**Issue by maxexcloo** [cronicle-edge/cronicle-edge#126]
When using the SSHX plugin with macOS, the base 64 decode fails as the parameter is -D instead of -d - is there any way to provide this as an option?

**Comment by mikeTWC1984** [comment]
At this point this command is hardcoded, so you can change via setting. You can still replace it (in the sshx-plugin.js file) on target machine, or maybe install posix component version of it.  Or perhaps use regular SSH plugin. I can add this as an option on the next release

**Comment by mikeTWC1984** [comment]
OK, after you upgrade to 1.9.5 you can add this param to SSHX plugin:
![image](https://github.com/user-attachments/assets/2a7a61c0-8ccd-4397-beb2-cb4ed23aae1c)
Then set darwin is target OS. It will just replace "-di" to "-D" in the temp script. I haven't tested it, so it still failing let me know
