### ISSUE TITLE
Cannot install without docker - Ubuntu 22

### ISSUE THREAD

**Issue by Shto1337** [cronicle-edge/cronicle-edge#129]
Many thanks for creating this version with additional features
I am interested in all the features this project brings but i am not interested in using docker.

I tried installing it on ubuntu 22, but it failed during the process

I have attached the log file.
[cronicle_install.log](https://github.com/user-attachments/files/16283863/cronicle_install.log)

```curl -s https://raw.githubusercontent.com/cronicle-edge/cronicle-edge/main/bin/install.js | node

Cronicle Installer v1.5
Copyright (c) 2015 - 2022 PixlCore.com. MIT Licensed.
Log File: /opt/cronicle/logs/install.log

Fetching release list...
Installing Cronicle v1.9.4...
Installing dependencies...
Running post-install script...
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'node_modules/zxcvbn/dist/zxcvbn.js'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/zxcvbn/dist/zxcvbn.js'
}

Node.js v22.4.1

ERROR: Failed to run post-install: Error: Command failed: node bin/build.js dist
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'node_modules/zxcvbn/dist/zxcvbn.js'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/zxcvbn/dist/zxcvbn.js'
}

Node.js v22.4.1


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"`

node -v
v22.4.1

npm -v
10.8.1

uname -a
Linux test-vm.test 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by Shto1337** [comment]
Same result with 
node -v
v20.15.1

npm -v
10.7.0

**Comment by mikeTWC1984** [comment]
@Shto1337  you use the installer that inherited form original cronicle. In order to build this edge version you need to bundle it. Clone the repo or download source to some folder, then cd to this folder and just run "./bundle". That script will install everything into dist folder (in the same directory). You can also do "./bundle --help"

**Comment by Shto1337** [comment]
I used the command

curl -s https://raw.githubusercontent.com/cronicle-edge/cronicle-edge/main/bin/install.js | node

Doesnt it use cronicle-edge from this repo?

**Comment by Shto1337** [comment]
What i mean is, it would be great if you could change and maintain the installer so that it installs this version of cronicle.

**Comment by mikeTWC1984** [comment]
Do you need this for some compatibility with older cronicle? New install method is way different, so I don't really support legacy installer. If you just need one-liner, you can do something like "git clone ... && ./cronicle-edge/bundle --options"

**Comment by Shto1337** [comment]
okay, no problem, i've managed to install it according to your instructions with the bundle command.

Thank you ! ❤️
