### ISSUE TITLE
Error: Failed to locate Secret: globalenv

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#13]
I can't open the tab "admin" - "configs". I only get the error message "Error: Failed to locate Secret: globalenv". Any idea what is missing?

**Comment by mikeTWC1984** [comment]
I guess you are running it on top of existing data folder? 
You need to init global/secrets/globalenv object in storage to make it work ( it supposed to be created during initial set up which you don't run if you have data folder already).  It might be possible create it with storage-cli, I'll check. Maybe I can add an option to auto generate this objrct

In general I meant this fork to run as a fresh install, and then  import jobs from original cronicle via import api to avoid any incompatibility issues.

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike,

thanks for the hint with the storage-cli.js. I was able to transport the settings from a scratch-installation to my system.

1. create the list: ./storage-cli.js list_create global/secrets
2. edit the item 0: ./storage-cli.js edit global/secrets/0 and paste:
```
{
        "type": "list_page",
        "items": [
                {
                        "id": "globalenv",
                        "encrypted": false,
                        "target": null,
                        "form": "props",
                        "data": "# dotenv style key/value pairs representing env variables\nmyvar = some_value"
                }
        ]
}
```
3. edit the list and set the length from 0 to 1: ./storage-cli.js edit global/secrets
4. error is gone!
