### ISSUE TITLE
Feature request: Add LDAPS support

### ISSUE THREAD

**Issue by Shto1337** [cronicle-edge/cronicle-edge#130]
Hello,

1. For security reasons, please add support for LDAPS because currently only LDAP is supported, being hardcoded

`
                        let ad = new ActiveDirectory({ url: ('ldap://' + domain) });
`

Maybe add it as a config variable.

2. In some environments, LDAP  may be blocked and LDAPS is enforced, but some prefer to skip SSL verification(e.g. error "UNABLE_TO_VERIFY_LEAF_SIGNATURE"). 

Thus, add the possibility, as a config variable to skip SSL verification via 

`NODE_TLS_REJECT_UNAUTHORIZED = '0';`

**Comment by mikeTWC1984** [comment]
Good point. Will do

**Comment by mikeTWC1984** [comment]
OK, now on 1.9.5 you can add this config:

```json
"ldap": {
 "url": "ldaps://dc.domain.com:636", 
 "tlsOptions": {
        "rejectUnauthorized": false
    }
}
```
