### ISSUE TITLE
Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by WolfgangDpunkt** [cronicle-edge/cronicle-edge#131]
I somehow can't manage to use SSH keys in the SSHX plugin.
No matter how and what I enter, I get the error message:

  _Error: Cannot parse privateKey: Unsupported key format_

Are special key formats necessary? I tried RSA 2048-bit and ED25519.

I entered it like this:

<img width="751" alt="grafik" src="https://github.com/user-attachments/assets/7d3ddfdf-bfdb-4889-bd28-fb909778c750">

I also tried removing all line breaks, I left out the parts at the top and bottom (-----BEGIN OPENSSH PRIVATE KEY-----), both without success.
What else can I do differently?
I don't want the SSH keys as files on the server.

Thank you very much!

**Comment by mikeTWC1984** [comment]
Oh, you need put multiline variables in double quotes. E.g.
SSH_KEY="gdfgfdg
dfgfdgdf
dfgfdg
"

Or if you on some older version, check version of dotenv package in package.json. Older version of it do not support multiline variables

**Comment by WolfgangDpunkt** [comment]
Thank you very much! The solution was obvious, but possibly it should be mentioned in the documentation.
Another observation is that ED25519 does not work, but RSA works without any problems.
