### ISSUE TITLE
Chain call count problem

### ISSUE THREAD

**Issue by iferencz** [cronicle-edge/cronicle-edge#134]
Hello everyone, I am using version 1.9.4. I encountered a problem when chaining. If I print the json data of the calling event multiple times when the event is running, the actual situation is that another event will only be called once. How can I call another event with the corresponding number of times? Thank you.
```
print(json.dumps({'chain': '{{ event_id }}', 'chain_params': {'key':'value'}}, ensure_ascii=False))
print(json.dumps({'chain': '{{ event_id }}', 'chain_params': {'key':'value'}}, ensure_ascii=False))
```

**Comment by mikeTWC1984** [comment]
I'm quite sure that chain message get processed once upon job completion. So you can't really launch jobs while your event is running. Neither you can launch multiple events at the end.

From the other side you can achieve this with calling rest api, just need to create api key
http://localhost/api/app/run_event?id=elw5qbmvv0p&post_data=1&api_key=API_KEY&key=value
