### ISSUE TITLE
issue - pid_file config is ignored by control.sh

### ISSUE THREAD

**Issue by Shto1337** [cronicle-edge/cronicle-edge#136]
If you try to modify from the config file, the variable "pid_file", the control.sh script does not know of this change.

For example, if i change in the configs,  "pid_file": "/var/run/cronicled.pid",

./control.sh stop
stop: Cronicle Daemon not running (no pid file)

ll /var/run/ | grep cronicle
-rw-r--r--  1 root    root       6 Aug 16 17:05 cronicled.pid

ps -auxwff | grep Cronicle
root      168029  0.7  1.2 1320716 105200 ?      Ssl  17:05   0:06 Cronicle Server

It seems its hardcoded inside the control.sh script:

PIDFILE=$HOMEDIR/logs/cronicled.pid

Also, afaik, all pid files should reside in /var/run/ by default and not in the logs folder.
https://superuser.com/questions/454449/linux-alternative-places-where-to-store-pid-file-instead-of-var-run

**Comment by mikeTWC1984** [comment]
OK, on 1.9.6 it should use pid file from config
