### ISSUE TITLE
LDAP authentication issues

### ISSUE THREAD

**Issue by rgcouto** [cronicle-edge/cronicle-edge#141]
Hello all,

I'm trying out this fork to check if I can successfully manage to login using LDAP (via JumpCloud), but this has been proven to be difficult to achieve, but maybe there's something wrong on my side that I'm simply not seeing.

I've currently even changed the `lib/user.js` file to hardcode the `opts` variable like described below:
```js
var opts = { 
	url: 'ldaps://ldap.jumpcloud.com:636',
	baseDN: 'uid=MY_USER,ou=Users,o=ORGANIZATION_ID,dc=jumpcloud,dc=com',
	password: 'MY_PASSWORD',
	tlsOptions: { 
		"rejectUnauthorized": false
	} 
}
```

I've also tried to login with the concatenation of the `user` variable with the `ad_domain` variable (which happens a couple lines below) disabled, but no luck either.

Checking out the logs, this is the only thing I get:
`[1726153623.194][2024-09-12 15:07:03][cronicle-edge-cronicle-edge-platform][47][User][debug][3][LDAP login failed][{"lde_message":"Invalid ldap packet","lde_dn":null}]`

What I know/tried to do:
- I've tried to look into the package code and can't find what might be wrong, but since the package is not being maintained anymore I wasn't sure if I got any reply there;
- Configuration strings from the LDAP server are correct, I've based my configuration from this URL from [JumpCloud](https://jumpcloud.com/support/use-cloud-ldap);
- I have confirmed that I have access to the LDAP server;
- I've tried to use `ldap://...:389`;
- I've also tried using the latest version of the `activedirectory2` package, version `2.2.0`.

Is there anyone who have had the same issue? If so, is there a way around this?

Thanks in advance.

**Comment by mikeTWC1984** [comment]
That's right. I don't think at current configuration you can make it work with LDAP other then AD version of it.
Current module just verifying user/password using simple binding. In order to make this binding, you need to use full DN, which in AD can be replaced with SamAccountName. The latter can be used as username too. Technically you can use full DN as username, but it will have some special characters that not allowed. In general, LDAP auth needs some svc account to lookup user by mail/CN/etc, then perform a binding. Actually it was the next thing on my plate to add, so I'll try get it some time soon.

**Comment by mikeTWC1984** [comment]
Yeah, I see it. Thanks for the PR. However, I think I'd need to refactor it to use just to use 1 library, not both. Both activedirectory2 and ldap-authentication are based on ldapjs which has been deprecated for a while, I'm thinking to switch to some other library.

**Comment by mikeTWC1984** [comment]
So looks like ldapts package is the only good option now (not based on ldapjs)

One of the good features of activedirectory2 package was  that it auto discovered root directory. Below is the snippet to do this using ldapts, which works with AD. Can you test it on your end with your LDAP? It should print something like "Entries DC=CORP,DC=COMPANY,DC=COM"

```js
const { Client } = require('ldapts');

const url = 'ldaps://ldap.jumpcloud.com:636';

async function getRootDSE() {
    const client = new Client({ url: url });
    const {searchEntries} = await client.search('', {
      scope: 'base',
      filter: '(objectClass=*)',
      attributes: ['namingContexts'],
    });


    console.log('Entries', searchEntries[0].namingContexts[0])
    client.unbind()
  
    //return searchEntries[0].namingContexts[0];
 }

 getRootDSE()
```

**Comment by rgcouto** [comment]
Hey!

That's nice that you've found that alternative. Give me a little bit of time so I can save some time here on my side to work on this, 
and I'll let you know!

**Comment by rgcouto** [comment]
Hey @mikeTWC1984 I've just tried it out, and I was able to succesfully login into my JumpCloud account. This solution is even better that the one I proposed initially since I don't even have to provide the administration account to search the user base of the AD.

I'm preparing a fix for the PR and I'll update it.

**Comment by mikeTWC1984** [comment]
@rgcouto  I just released version version 0.10, it has quite a rework of LDAP/AD. Check release notes. It should cover LDAP login and also group auth

**Comment by rgcouto** [comment]
Hey @mikeTWC1984 

I'm trying to setup v1.10.0, but I'm having some problems with it. It seems that the `ldap` config field is not being parsed correctly, as I'm always getting "Invalid LDAP url: unedefined" on the logs.

On the `ldap` config field I've got something like:
```json
{
      "url":"ldaps://ldap.jumpcloud.com:636",
      "tlsOptions":{
         "rejectUnauthorized":false
      },
      "bindDN":"ou=Users,o=1234567890abcdef,dc=jumpcloud,dc=com"
}
```

On the `users.js` file I've added this code for better debugging after some failed attempts:
```javascript
...
let opts = self.server.config.get('ldap') || {}

self.logDebug(3, "--------------------------")
self.logDebug(3, opts)
self.logDebug(3, "--------------------------")
self.logDebug(3, opts.url)
self.logDebug(3, "--------------------------")
self.logDebug(3, typeof opts.url)
self.logDebug(3, "--------------------------")
...
```
These are the current logs:
```
[1728922842.774][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][--------------------------][]
[1728922842.774][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][{	"url":"ldaps://ldap.jumpcloud.com:636",	"tlsOptions":{		"rejectUnauthorized":false	},	"bindDN":"ou=Users,o=1234567890abcdef,dc=jumpcloud,dc=com"}][]
[1728922842.774][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][--------------------------][]
[1728922842.775][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][][]
[1728922842.775][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][--------------------------][]
[1728922842.775][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][undefined][]
[1728922842.775][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][debug][3][--------------------------][]
[1728922842.775][2024-10-14 16:20:42][cronicle-edge-cronicle-edge-platform][117][User][error][Invalid LDAP url: undefined][][]
```

So, the `ldap` field is being loaded correctly into the `opts`, but then it can't parse it, because I should see the `url` on the second output, but instead of that I'm seeing an empty value, even though the `opts` variable has data. I've already tried to do some `let opts = JSON.parse(...)`, but the result is the same. 

Do you see something that I'm not seeing? 

Thanks in advance.

**Comment by mikeTWC1984** [comment]
Looks weird. In you debug try to print those things:
typeof opts
Object.keys(opts)

**Comment by mikeTWC1984** [comment]
Also, go to admin tab, config section, click on "Config Viewer"
It should show actual current configs. Perhaps there is some overlapping with configs set in UI and config.json, so ldap property might get broken. This is how healthy config should look:
![image](https://github.com/user-attachments/assets/25c28781-fee8-4b69-86cb-0debcd815516)

**Comment by mikeTWC1984** [comment]
Also, try to remove any ad_* like key from that config section (under admin/config)

**Comment by rgcouto** [comment]
> Also, go to admin tab, config section, click on "Config Viewer" It should show actual current configs. Perhaps there is some overlapping with configs set in UI and config.json, so ldap property might get broken. This is how healthy config should look: ![image](https://private-user-images.githubusercontent.com/31977106/376380616-25c28781-fee8-4b69-86cb-0debcd815516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Mzg4ODAsIm5iZiI6MTcyODkzODU4MCwicGF0aCI6Ii8zMTk3NzEwNi8zNzYzODA2MTYtMjVjMjg3ODEtZmVlOC00YjY5LTg2Y2ItMGRlYmNkODE1NTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIwNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOTM1ZmNiMjA3NTVlMTM0Y2FlMWUxM2NjODc5ZmJmMTRiYmQwZThlNzE1ZDM5YTkyMDZhNDg5MWZiN2FkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.miLE0aijbbKdY0kJBfv5BTLtml6tafnLXItVNDfKurY)

I think the problem is here! When I add the `ldap` config field from the UI, it stores it as simple text and that is why it can't parse it.
![image](https://github.com/user-attachments/assets/14a000a9-93b4-4e51-8c57-8c9abd373da2)

If I add the `ldap` config field directly in the config file, then it loads well and tries to log in using the LDAP server. 

I still had to do some changes on the `ldap` object, namely to the `bindDN` field. JumpCloud says that my `SvcAccount` is a field of type `uid` and not `cn`. After this change, I got it to login perfectly!

**Comment by mikeTWC1984** [comment]
OK, perhaps you put entire ldap config a single property or something like this. Each individual key should be listed separately, nested property should be dot separated. E.g.
![image](https://github.com/user-attachments/assets/a7712f7c-e46f-4890-a810-8fee185a171b)

Regarding that bindDN/ScvAccount issue, did you update configuration or something on user.js to make it work?

**Comment by rgcouto** [comment]
Yes, I was putting everything together, there's a JSON option there 😂. Anyway, that would have done it, for sure. I didn't remember to do that! 

Regarding changes on `user.js`, no, I didn't change anything on that file. Just changed the `bindDB` string right on the config file from:
`"bindDN":"cn=SvcAccount,ou=Users,o=1234567890abcdef,dc=jumpcloud,dc=com"`
to:
`"bindDN":"uid=SvcAccount,ou=Users,o=1234567890abcdef,dc=jumpcloud,dc=com"`
