### ISSUE TITLE
Possible to migrate from standalone jhuckaby/cronicle to cronicle-edge Docker?

### ISSUE THREAD

**Issue by sirjmann92** [cronicle-edge/cronicle-edge#145]
Hello, I've been using the base Cronicle as a natively installed application in Linux on multiple machines for quite a while. I'd like to transition to cronicle-edge in a Docker environment. I've tried copying the existing /opt/cronicle/data directory and files into my Docker compose project directory for cronicle-edge but that didn't seem to do the trick. I was able to start the container and login with the default credentials, but no jobs or other data was available. I also tried copying other files and directories from the default installation to the Docker project directory and mapping the volumes in my compose file but none of that seemed to work.

At one point, I tried mapping some of the files and directories directly but then the Docker container/image logs balked about files not being available, so I'm guessing there are some internal dependencies. I tried extracting the files from the image to my host and then mapping then, and this allows the container to start but still doesn't have my jobs or user accounts or other data available, it's like a new Docker install.

Is it possible to migrate and maintain user accounts, jobs, and worker data?

Thanks in advance and apologies for opening an issue on this, but I couldn't find any information about this...

**Comment by mikeTWC1984** [comment]
Hi @sirjmann92 

Thanks for using this fork. So this edge fork is not much different from original cornicle, and docker is not much different from desktop linux. So migration is definely possible.
I can't think of any obvious issue if you want to copy data folder, but there might be some.
I'd typically suggest import metadata (events/categories/users/etc), and not job history/logs
to do that, in old cronicle:
./bin/control.sh export
Then copy output of this command (some json lines). Go to a fresh install of edge fork, go to Schedule tab. You should see "import" button. Copy/paste export output. Then it should import all objects besides servers and plugins (which is fine unless you are using custom plugins).

Try that and see if it works. If you really need jobs and logs, I can do closer look.

**Comment by sirjmann92** [comment]
Thanks. This mostly works. I'm not sure I'll stick with it. I like the dark mode, and I like the idea of containerizing Cronicle, mainly for dependency and maintenance sake. However, there are some things that don't get imported and need to be reconfigured, and any scripts that depend on files anywhere on the host need to be mapped. Some things can't properly be mapped because they mess with the files in the container (anything in PATH can potentially break the container).

I think I'll stick with the standard version and either come up with my own way of implementing dark mode (other than browser plugins) and/or wait for Orchestra (Cronicle v2).

Thanks much, this is still a cool and fun project! :)

**Comment by mikeTWC1984** [comment]
If you need dark theme - it's built in into base cronicle framework. It's really easy to add, the only reason it's not on main cronicle is because of some minor styling issues (jhuckaby didn't want spend time on polishing it while working on v2). But it's really minor, you can add it for your self.

**Comment by sirjmann92** [comment]
Any chance you could give me a little more direction? I've tried replacing the /htdocs directory but apparently it's a little more involved than that. Tried replacing just specific files that are named the same between edge and standard, also didn't work. I was able to get the login screen in dark mode and I was able to log in, but then it just gets stuck at waiting for master server. I probably didn't go far enough and then went too far, or vice versa... either way I couldn't quite get it working. Any tips you have would be greatly appreciated.

**Comment by sirjmann92** [comment]
@mikeTWC1984 - I've done some digging in the code, and it seems like it should be straightforward, but I'm not a developer and I'm struggling to find the right combination :/ It looks like the css classes are there, the js functions are defined, even including the icon that should be displayed depending on the user's preference. What I can't figure out is exactly which function to call and/or where to place it in the HTML to make the toggle appear. I tried overriding the colors with dark colors, tried removing all reference to light theme in the js functions, in multiple files, and deleted my browsing history and used incognito windows so caching wouldn't be an issue.

So far, no luck...

If you have the time, and would be so kind, could you give me a bit more information on how to enable this? If not, that's fine, I'll keep digging and trying until I get it ;) Knowing it's there is a great help in and of itself.

Thanks again

**Comment by mikeTWC1984** [comment]
To try it out - copy paste this into browser console:
app.toggleTheme()

Then just locate that function in my fork code, there will be few lines of html, and see how that block is different from original cronicle.

**Comment by sirjmann92** [comment]
Got it! Got it working!

Took some tinkering, but I finally got it. Thank you very much for the info!

Now I need to make a backup and/or script to re-apply the changes after an update.
