### ISSUE TITLE
Child spawn error: node: Child process failed to spawn 

### ISSUE THREAD

**Issue by serveryang** [cronicle-edge/cronicle-edge#149]
use 'shell-script' plugin run the default shell script, got error:
`Error: Child spawn error: node: Child process failed to spawn (Check executable location and permissions?)`
![image](https://github.com/user-attachments/assets/434abff5-b628-474b-8354-1dc55bc9c5c0)

if i open then `Debug Opts`, checked `Sudo`, then the job run success.

why not use root user excute the command?

$ node --version
v16.20.2

cronicle-edge run by `root` user:
![image](https://github.com/user-attachments/assets/55295c68-e47e-45f8-9865-f604281413e8)

**Comment by mikeTWC1984** [comment]
Hi. Shell plugin is set to run by user cronicle, which I create in docker images, but you won't have it if running locally. Go to plugin settings and update "Run As" option (either keep blank or use some user that exist)

**Comment by serveryang** [comment]
Ok，i found it in 'Advanced Options'.
