### ISSUE TITLE
Error: WF Signature is not set

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#15]
Hi Mike,

I found another problem with your workflow plugin. Sometimes the execution fails with the error "Error: WF Signature is not set". If I run the same event again, the execution succeeds.

Any idea? 

```
Job Schedule [Concurrency: 1, From Step: 1]
 RUNNING(2): 
 [1] (mia01p) sftp.transfer - ice.endex.futures.config Prod (ekye9e8p9fx) 
 [2] (mib1p) sftp.transfer - ice.futures.eu.commodities.prod.config (ekvcf26b80e) 
 ──────────────────────────────────────────────────────────────────────────────────
Workflow Started @ 2/17/2022, 4:00:00 AM
 │  
 ├───────> starting (mia01p) sftp.transfer - ice.endex.futures.config Prod
 │  

# Job failed with error: Failed to fetch job details: Error: Failed to fetch key: jobs/jkzqearc3f4: File not found
# 3 retries remain (1 min delay)

# Job ID: jkzqeaqx7dr
# Event Title: (miwf1p) sftp download ICE Prod
# Hostname: XXXX.YYYY.de
# Date/Time: 2022/02/17 04:01:06 (GMT+1)

/opt/cronicle/bin/workflow.js:8
if(!process.env['WF_SIGNATURE']) throw new Error('WF Signature is not set')
                                 ^

Error: WF Signature is not set
```

another run - same host

```
Job Schedule [Concurrency: 1, From Step: 1]
 RUNNING(2): 
 [1] (mia01p) sftp.transfer - ice.endex.futures.config Prod (ekye9e8p9fx) 
 [2] (mib1p) sftp.transfer - ice.futures.eu.commodities.prod.config (ekvcf26b80e) 
 ──────────────────────────────────────────────────────────────────────────────────
Workflow Started @ 2/16/2022, 7:33:17 AM
 │  
 ├───────> starting (mia01p) sftp.transfer - ice.endex.futures.config Prod
 │  
 │ ⬤ (mia01p) sftp.transfer - ice.endex.futures.config Prod (job jkzp6h6v64i) completed [1/2] at 7:33:21 AM
 │      elapsed in 00:00:03    
 │
 ├───────> starting (mib1p) sftp.transfer - ice.futures.eu.commodities.prod.config
 │
 │ ⬤ (mib1p) sftp.transfer - ice.futures.eu.commodities.prod.config (job jkzp6ha254j) completed [2/2] at 7:33:26 AM
 │      elapsed in 00:00:03    
 │
 │
Workflow Completed @2/16/2022, 7:33:26 AM  
```

**Comment by mikeTWC1984** [comment]
Looks like the first run with error is when you retry to run failed job
# Job failed with error: Failed to fetch job details: Error: Failed to fetch key: jobs/jkzqearc3f4: File not found
# 3 retries remain (1 min delay)
I guess in this case job goes through a bit different route and signature not get assigned. I'll check and update soon.

**Comment by mikeTWC1984** [comment]
This is used for authentication. One way is to generate API key like you just explained, but it requires extra work / secret sharing. This WF_SIGNATURE is generated internally (hash from secret_key) and is valid only while wf job is running. So auth will work out of the box.

**Comment by dheise-rheinenergie-trading-com** [comment]
Thanks for the explanation and for the really fast fix! We will try the new release in the next time.

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike,

the fix doesn't work. I still get the error "Error: WF Signature is not set". I hope you can reproduce it:

event 1:
- plugin: workflow (triggers event 1.1 and 1.2)
- retry if failed: 2

event 1.1: 
- plugin: shell
- command: "exit 0"

event 1.1: 
- plugin: shell
- command: "exit 1"

```
Job Schedule [Concurrency: 1, From Step: 1]
 RUNNING(2): 
 [1] Test Exit 0 #1 (eksztwnnzuz) 
 [2] Test Exit 1 (ek61ye6mwqe) 
 ──────────────────────────────────
Workflow Started @ 2/18/2022, 11:07:55 AM
 │  
 ├───────> starting Test Exit 0 #1
 │  
 │ ⬤ Test Exit 0 #1 (job jkzs90wys4u) completed [1/2] at 11:07:56 AM
 │      elapsed in 00:00:00    
 │
 ├───────> starting Test Exit 1
 │
 │ ⬤ Test Exit 1 (job jkzs90xtz4v) completed [2/2] at 11:08:00 AM
 │      elapsed in 00:00:02  
 │    Error: Script exited with code: 1  
 │
 │
Workflow Completed @2/18/2022, 11:08:00 AM  

# Job failed with error: WF - 1 out of 2 jobs reported error
# 2 retries remain (2 sec delay)

# Job ID: jkzs90wt84t
# Event Title: test workflow
# Hostname: XXXX.YYYY.de
# Date/Time: 2022/02/18 11:08:02 (GMT+1)

/opt/cronicle/bin/workflow.js:8
if(!process.env['WF_SIGNATURE']) throw new Error('WF Signature is not set')
                                 ^

Error: WF Signature is not set
    at Object.<anonymous> (/opt/cronicle/bin/workflow.js:8:40)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by mikeTWC1984** [comment]
Just realize - that WF signature only get generated if pluginid == "workflow" (generated during setup). If you created this plugin manually the id will be auto-generated. 
https://github.com/cronicle-edge/cronicle-edge/blob/26bf4b88f7c1567cff7af3aca67fee395c5be629/lib/job.js#L504
I guess for now you can use api key instead. I'll probably switch to some plugin option rather than plugin id on the next release.

**Comment by mikeTWC1984** [comment]
OK, you should now be able to enable wf signature generation via plugin setting, hopefully this would help
![image](https://user-images.githubusercontent.com/31977106/155182126-bea0af9a-a106-4f32-a5f1-28e9b472bcc2.png)

**Comment by dheise-rheinenergie-trading-com** [comment]
I have subsequently changed the ID of the manually created plugin to "workflow". So everything works as it should.
