### ISSUE TITLE
page loop refresh after login

### ISSUE THREAD

**Issue by serveryang** [cronicle-edge/cronicle-edge#151]
i debug in local, fond in `monitor: function()`: 
`   var result = app.page_manager.click( page_name, page_args );
    if (result) {
    this.old_loc = this.loc;
    if (this.old_loc == 'init') this.old_loc = config.DefaultPage || 'Main';
    this.loc = anchor;
    }
    else {
    // current page aborted navigation -- recover current page without refresh
    this.go( this.loc );
    }`
will loop refresh, and can't debug cronicle.

**Comment by mikeTWC1984** [comment]
Yeah, there are some edge cases when loop/refresh might happen (although as far as I remember it should be multi node cluster). How exactly you are debugging it?
