### ISSUE TITLE
Issue with triggering events remotely

### ISSUE THREAD

**Issue by rgcouto** [cronicle-edge/cronicle-edge#154]
Hey there again!

# The problem
We've noticed there's a change in the behaviour of the API endpoint `api/app/run_event/v1` when we migrated from cronicle to cronicle-edge.

As per documentation from original repository (https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#event-data-format) we can customize the parameters we pass to a job when remotely calling the job to execute.

Indeed we have some places where we do a simple curl to that endpoint and replace some params, namely, the `url` param from the `HTTP Request` plugin to something more custom we need it to be. We do this be cause we don't want to expose the content of the 
`Request Headers` field and because we want the Cronicle instance to do the request.

Currently what is happening is that the `url` field is not being replaced with the payload one but rather keeping the original.

# Example

The configuration:
![image](https://github.com/user-attachments/assets/d811c6f6-43eb-4b16-b15d-0bdb18026b01)

The `curl`:
```
curl --insecure \
        --header "Content-Type: application/json" \
        --request POST \
        --data "{\"id\":\"${CRONICLE_EVENT_ID}\", \"params\": {\"url\": \"https://sonarcloud.io/api/permissions/apply_template?projectKey=${ORGANIZATION_NAME}_${CI_PROJECT_NAME}&organization=${ORGANIZATION_NAME}&templateName=${PROJECT_GROUP}-permission-template\"}}" \
        "https://my-cronicle-url/api/app/run_event/v1?api_key=${CRONICLE_API_KEY}" | jq -r .ids[0]
```

What is happening:
![image](https://github.com/user-attachments/assets/ea655f23-5ae7-462a-8d51-955a2a30c0a1)

# Conclusion
The `url` field is not being replaced by the one from the request, where indeed it should, right?

**Comment by mikeTWC1984** [comment]
@rgcouto  yeah, it was one of the security enhancement. The idea was to prevent user with "run_event" permission only to alter scripts when running event manually. Such user can only supply extra arguments to alter script behavior.
You can add edit/create privilege  to your api key to make it work.

**Comment by mikeTWC1984** [comment]
Btw, you can use placeholders to alter URL. E.g. you can add key/value pair on API url, e.g. FOO=BAR. 
```bash
curl "http://localhost:3012/api/app/run_event?id=em3639vfqbm&api_key=123456&FOO=BAR"
```
This will attach property FOO to you job object. Then you can refer to it in url you set in plugin this way:
https://sonarcloud.io/api/permissions/apply_template?projectKey=[/FOO]

**Comment by rgcouto** [comment]
Hey @mikeTWC1984 thanks for the reply! 

I completely forgot that a token could have different levels of privileges in this version. I just changed it to also be able to edit the job 🤞🏻 hopefully it works.

Regarding the second approach, sometimes we change the whole url because of having different parameters needs, so maybe we're better off with the first approach. 

We'll give it a try! 

Thanks again!
