### ISSUE TITLE
workflow - pause options

### ISSUE THREAD

**Issue by josephdadams** [cronicle-edge/cronicle-edge#155]
Let's say I have 3 items I want to run in a workflow. It kicks off at 8am. It should run the first item, wait x seconds/minutes/whatever, then do the second item, etc. Is there a way of doing this short of making a "sleep" plugin and keeping track of the max job run time?

**Comment by mikeTWC1984** [comment]
you can just create a shell script event for this. Like 
```bash
sleep $JOB_ARG
```
JOB_ARG is env variable which comes from workflow argument

**Comment by josephdadams** [comment]
Great idea!
