### ISSUE TITLE
Add discord support with webhooks?

### ISSUE THREAD

**Issue by greenaar** [cronicle-edge/cronicle-edge#156]
https://github.com/jhuckaby/Cronicle/issues/591 has a fix in for sending to discord via webhook, could this be ported to cronicle-edge?

tl;dr duplicating hook_data.text  to hook_data.content.

Thanks!

**Comment by mikeTWC1984** [comment]
I think you can achieve this by setting textkey = content, like in demo setup it's  set to markdown:
![image](https://github.com/user-attachments/assets/17b1ca36-8134-438e-8f97-0c326805f153)

**Comment by smartin015** [comment]
Apologies for reviving this thread - just wanted to add on a couple things:

- I can't seem to set a text key for the universal hook - adding a `universal_web_hook.textkey` entry didn't do anything.
- For others stumbling across this issue, referencing in notifications is done by just putting the word `discord` in e.g. the `Web Hook URL (complete):` field of the event edit page, after setting up the `web_hooks.discord.*` fields as above.

Is there a way to set `textkey` for the universal webhook that I'm missing?

**Comment by mikeTWC1984** [comment]
Try to just set universal_web_hook = discord

**Comment by smartin015** [comment]
I tried with 

universal_web_hook = `discord`
web_hooks.discord.textkey = `content`
web_hooks.discord.url = `https://discord.com/api/webhooks/<redacted>`

On a shell Event:

```
#!/usr/bin/env bash

exit 1
```

with all of the notification config options left empty for the event itself.

Running the event manually caused it to terminate in a failure (which is good) but no message is visible on the Discord channel that the webhook points to. I also tried again after pressing the "Reload" button on the Configs page on the off chance it was needed, still no luck.

I do see a discord message when I specify `discord` under `Web Hook URL (complete)` of the event, so the URL and text key config are correct - it just doesn't seem to be accessible from the `universal_web_hook`. I can get by with editing the notification config for every event, but it'd be handy to have the universal hook supported and I wouldn't have to worry about parity between the event configs.

**Comment by mikeTWC1984** [comment]
OK, I guess universal_web_hook works a bit different then. Shouldn't be a problem to follow same pattern, will do on the next release.
One more thing - as far as I remember universal_web_hook  is extremely verbose. Instead you can use admin_web_hook property.  It will be publishing messaged for much smaller range of events:
- CRUD operation on any kind of items
- job failures
- user login
- backup/import

**Comment by smartin015** [comment]
Thanks for the pointer on `admin_web_hook` - I use it exclusively for posting a pointer to job failures, so less verbose is good :)

I'll stick to per-event notifications until the next release. Thanks!

**Comment by mikeTWC1984** [comment]
After closer look, it seems like if you'd set universal_webhook as object it should work, e.g. smth like

```json
"universal_web_hook"  :  {
     "url": "https://discord.com/api/webhooks/<redacted>",
     "textkey": "content"
}
```

Perhaps if you set it via config it got messed up by some reason.  Just check how it looks in config viewer
![image](https://github.com/user-attachments/assets/f5f6e3a1-0e3e-4faf-a0c6-3d8cab877624)
