### ISSUE TITLE
Is it safe to create an event using your own id?

### ISSUE THREAD

**Issue by Shto1337** [cronicle-edge/cronicle-edge#159]
Hello,

We want to keep track of our own cronicle events using git. By doing so, we need to keep track of the event ID's.

Is it safe to use our own event ID's when creating them?
Like "proj-app-123"?

Thank you

**Comment by mikeTWC1984** [comment]
Yeah, I think it should not be a problem. How are you going to assign those ID though? I recall there was some trick of doing it via title naming (like if you name it [someId|title] or so).
The only concern here is that ID should be unique. If you do it via standard event create API, it will be enforced (bot ID and Title should be checked for uniqueness). But if you interact with a storage directly (like via storage-cli) it's not enforced.

**Comment by Shto1337** [comment]
>>How are you going to assign those ID though?
I will use the same name for .title and .id and will be unique per event, meaning no other event will have the same title/id

Will do it via the event create API.

Thank you

If possible look into my other "issue": https://github.com/cronicle-edge/cronicle-edge/issues/135
