### ISSUE TITLE
upgrade cronicle-edge with ./control.sh upgrade

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#19]
Hi Mike,

I noticed updating cronicle-edge with the default command ./control.sh upgrade is not possible. The script fetches the releases from the classic cronicle.
I patched 3 lines in the install.js to target your repo:

```
var gh_repo_url = 'http://github.com/jhuckaby/Cronicle';
var gh_releases_url = 'https://api.github.com/repos/jhuckaby/Cronicle/releases';
var gh_head_tarball_url = 'https://github.com/jhuckaby/Cronicle/archive/manager.tar.gz';
```

to 

```
var gh_repo_url = 'http://github.com/cronicle-edge/cronicle-edge';
var gh_releases_url = 'https://api.github.com/repos/cronicle-edge/cronicle-edge/releases';
var gh_head_tarball_url = 'https://github.com/cronicle-edge/cronicle-edge/archive/manager.tar.gz';
```

now updating seems to work for my systems. Could you fix this (I have to learn how to do pull requests ;-) )?

**Comment by dheise-rheinenergie-trading-com** [comment]
I did a pull request. I hope is ok for you; https://github.com/cronicle-edge/cronicle-edge/pull/20

**Comment by mikeTWC1984** [comment]
Ok, thanks. Just replace manager with main (in your fork main branch)

**Comment by dheise-rheinenergie-trading-com** [comment]
Fixed. But I suppose, the URLs are normally not used.
