### ISSUE TITLE
Stuck on waiting for master server

### ISSUE THREAD

**Issue by krazyjakee** [cronicle-edge/cronicle-edge#2]
Docker image version: cronicle/cronicle:edge-1.3.3

I followed the "Running using docker run" guide here: https://github.com/cronicle-edge/cronicle-edge/tree/main/Docker and copied in the sample config and setup files and running the "manager" command.

When running the container I see a login screen and can login. I see the main application for a moment and then the popup starts with the "waiting for master server" message and loading bar.

I have tried to
- restart the service.
- wait
- Modify the config to use various base app urls

Nothing has worked so far. Any help would be appreciated.

**Comment by mikeTWC1984** [comment]
This situation usually means that hostname does not match "Manager Group" regex. Probably you are mapping some existing data folder, that was used by other cornicle instance or so. 

I just tried the latest image, can't repro. Try those diagnostic steps:

1) start a temp interactive container without any volume mapping 
```bash
  docker run -it --rm -e CRONICLE_manager=1 -p 3012:3012 cronicle/cronicle:edge bash
```

2)  Type "manager" command.  Check browser in a few seconds, manager=1 should start it up immediately. 
 If you keep seeing "Waiting for Manager":
  go back to terminal, stop "manager" process and return to bash
  type this to see hostnames:  storage-cli.js get global/servers/0
  then this to see groups: storage-cli.js get global/server_groups/0
 
 make sure current hostname matches main group regex

**Comment by mikeTWC1984** [comment]
Also try to test without "manager=1". In this case you should see "Server is eligible to become manager" in the log output after you type "manager" command (if everything is OK)

**Comment by krazyjakee** [comment]
I didn't do anything and it just started working. I have no idea why, sorry.

**Comment by mikeTWC1984** [comment]
Good. If you use chrome, that also might be related to caching.
