### ISSUE TITLE
In a weekly schedule, extra time runs also on non selected days

### ISSUE THREAD

**Issue by atellier** [cronicle-edge/cronicle-edge#23]
Hi,

I have set up a weekly schedule with some specific days (M->F) that should run from 7am to 4pm included, every 20min. So I have a schedule with hours from 7am to 3pm and with 00:00, 20:00, and 40:00 as my minutes - I have also added an extra time (16:00) to cover for 4pm only. I would have expected that 4pm schedule to run only M-F and not all the days of week. Is that by design and if so, is there any way to have that 4pm job only run on the selected days (without having to create a separate job altogether just for that time)?

Thank you

**Comment by mikeTWC1984** [comment]
That's correct. "Extra tick" works as a completely separate schedule. Actually I had in mind to extend functionality of this type of schedule, e.g. you can specify it as something like MON,FRI@3PM. You may try to experiment with that, you just need modify this function:
https://github.com/cronicle-edge/cronicle-edge/blob/84c914fc62110ac17c08b246cc2a9f727c291fe4/lib/scheduler.js#L260
for now it gets an array of timestamps from that tick schedule and checks if current time is in this array. 

From the other side workflow plugin could be a good enough solution for such problems. It lets you run same exact job, just at different schedule.
