### ISSUE TITLE
pending jobs - mistakenly moved column "Actions" in "Active Jobs" 

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#26]
only appears when a event is listed as pending:

![image](https://user-images.githubusercontent.com/73586581/166658978-8bcf8580-7557-4d28-a33a-be69a6fe8852.png)

**Comment by mikeTWC1984** [comment]
Good catch. Will fix it soon. 
You were also right about schedule page rendering, it's not browser issue.  I released 1.5.9 earlier to test upgrade via "control.sh upgrade", it get's broken when your remove .map files (I do it for container). I'll release 1.5.10 later today to fix all the issues

**Comment by dheise-rheinenergie-trading-com** [comment]
now it shows up correctly. thanks for fixing.
