### ISSUE TITLE
[User][error][api][Missing parameter: manager][]

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#3]
I tried to migrate my existing cronicle servers to your edge installation, but I fail while adding the worker to the existing cluster. 

my procedure:

- I have an running cluster with 3 cronicle servers (version 0.8.56)
- I took a new server and installed your edge fork (version 1.3.3)
- I start the new worker with the following command - using an existing config and my current data folder
`
docker run -it --net=host --mount 'type=bind,source=/tmp/config.json,destination=/opt/cronicle/conf/config.json' --mount 'type=bind,source=/mnt/dua/cronicle/,destination=/mnt/dua/cronicle' cronicle/cronicle:edge manager
`
- the server comes up and shows me a "Waiting for manager server..." message
- I login into my master and try to add the new server to the cluster
- I get the error "Error: Failed to add server to cluster: rtbpme01: Missing parameter: manager"
- the docker shows me the error "[rtbpme01][9][User][error][api][Missing parameter: manager][]"

I also tried to use an exsiting worker from my cluster:
- stop cronicle
- start cronicle-edge with the original config/data directory
- the known cluster node disappears automatically after coming up
- I can't readd the worker
- If I stop cronicle-edge, start cronicle, I can readd the worker to the cluster

What means the error message and how can I fix it?

**Comment by mikeTWC1984** [comment]
You need to use "worker" command as entry point on worker nodes:
``` bash
docker run  -d cronicle/cronicle:edge worker
```
manager commands will set up storage on initial run

I'd also recommend to set up swarm cluster for multi-node setups (using persistent hostnames and overlay network). Here is some sample docker compose
https://github.com/cronicle-edge/cronicle-edge/blob/main/Docker/LocalCluster.yaml

**Comment by mikeTWC1984** [comment]
Also, check out portainer if not yet. It's a GUI to manage docker/swarm cluster. Very easy to install. Once you have it you can just copy/paste compose file, and then update images or configs with one click.

**Comment by dheise-rheinenergie-trading-com** [comment]
Mixing a classic Cronicle Server and Cronicle Edge worker doesn't work. A fresh installation on all servers fixed the problem.
