### ISSUE TITLE
Feature request: run docker commands

### ISSUE THREAD

**Issue by helmut72** [cronicle-edge/cronicle-edge#31]
Would be great to run docker commands from the existing image. For now I create an own image, add docker-cli ~~and sudo packages, also add cronicle user to sudoers file~~

Thank you.

Edit: I saw that there is an option to run shell scripts (docker-cli) also with root.

**Comment by mikeTWC1984** [comment]
Ok, is running in sudo mode is your main concern? If so, just update shell plugin setting to use root. My default image use non-sudo user ("cronicle") to run shell scripts. This way you can limit interaction with filesystem by default user. Shell plugin also has an option (for admin only) to execute script as main process users (root by default), but it's not a persistent setting.

**Comment by helmut72** [comment]
No, running as root is clarified, I found the setting (my edited text). Feature request is adding docker-cli to the image to run docker commands.

**Comment by helmut72** [comment]
> I guess each user would need it's own custom dockerfile anyway.

Yes, of course. Therefore and not to blow up my custom image I thought to use docker-cli in my bash scripts ... `docker run ffmpeg`... `docker run tesseract` ... `docker run powershell`... but docker-cli is needed :wink:

And yes, I also think about using it for CI/CD stuff.

**Comment by mikeTWC1984** [comment]
FYI, I added dockerode package on the new release. So you can use it instead of docker cli. CLI will take over 200MB of space (on alpine) but this package is just few megs or so.
Here is a sample script for "docker run"
```javascript
#!/usr/bin/env node

const Docker = require(`/opt/cronicle/node_modules/dockerode/`)
const docker = new Docker()

let cmd = "sleep 10; uname -a"

let options = {
 AutoRemove: true   // docker run --rm 
}
// https://docs.docker.com/engine/api/v1.37/#tag/Container/operation/ContainerCreate

docker.run("alpine", ["sh", "-c", cmd], process.stdout, options)
```

I might add some plugin/s for docker later. Btw, if you can ssh to the machine with docker you can use new plugin I created to apply yaml/Dockerfiles.

**Comment by helmut72** [comment]
Thanks. Will have a look at it, but it's just for a short test. I'm a lot more used to Bash scripting combining it with standard tools like sed, jq, awk, curl and so on ... than Javascript. I avoid Javascript for own stuff, which are mostly shell scripts.

cronicle-edge is 159MB in size. Using this a as base image:

```
FROM cronicle/cronicle:edge

ENV LANG C.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL C.UTF-8

RUN apk add --no-cache ca-certificates tzdata docker-cli
```

... becomes 213MB in size. Using other docker images with `docker run` would be a lot bigger than this few 54MB.

But anyway. Just close this issue if you want to add docker-cli command into your base image and also close this issue if you don't want to add it. It's your project ;) Then I will continue with an own image.

I just asked for adding docker-cli, not for dockerode. Adding a module like dockerode is more another issue?

**Comment by mikeTWC1984** [comment]
It was more like a heads-up that you have docker capability almost for free now. I added dockerode for the future use (for plugins and maybe UI elements). If you just need orchestrate docker (run containers on schedule or build images on webhooks) that is more than enough. For your custom admin stuff you obviously need your own set of tool, maybe even some different base image.

Anyway, I want to keep one core image with bare minimum of packages for simple demos. I thinking to create another image for s3 users (aws sdk alone is 150MB). Maybe another images based on Ubuntu/Centos (a lot of stuff just won't run on alpine) I guess some version for sysadmins could be useful, but I guess it should include a good set of tools then, not just docker (share your Dockerfile).  Just need to set up github action to maintain all this :)

Speaking of image sizes, I realized latest image is 200MB. 160MB didn't sound right either, so I did some clean up, and the new size should be within 120MB (will reload it soon). And you are right, docker-cli is much smaller, I compared to the full docker package. But still 50MB sounds kind of beefy just for client

**Comment by helmut72** [comment]
Ok, good ideas!

**Comment by helmut72** [comment]
> const Docker = require(`/opt/cronicle/node_modules/dockerode/`)

Is this still included?

**Comment by helmut72** [comment]
Ok, thanks for clarify. Also SSH plugin is removed? I don't see his option:
![](https://user-images.githubusercontent.com/31977106/182756155-d551f17b-9713-4b87-9bb9-2f6c62d207c3.png)

How to install any module? I exec into the container and tried to install dockerode with `npm (or node) install dockerode`, but doesn't work. I'm  a JS noob.

**Comment by mikeTWC1984** [comment]
Strange, perhaps you don't have this plugin in you storage

I see this plugin on the fresh image
```
docker run -it --rm -p 3012:3012 cronicle/edge manager
```

yes, you need to do "npm install dockerode".  But you need also npm to be install, I usually do not include it in the images. So do "apk add npm" first.

**Comment by helmut72** [comment]
> Strange, perhaps you don't have this plugin in you storage

I did some tests today. Starting from scratch SSH Plugin is there. I will close this issue, because of your clean up.
