### ISSUE TITLE
mail_options doesn't work

### ISSUE THREAD

**Issue by helmut72** [cronicle-edge/cronicle-edge#36]
In the webinterface I add in `admin -> configs -> add key` following:

```
config title: mail_options
type: json
value:
{
    "secure": false,
    "auth": {
        "user": "user",
        "pass": "pass"
    },
    "tls": {
        "rejectUnauthorized": true,
        "requireTLS": true
    },
    "connectionTimeout": 10000,
    "greetingTimeout": 10000,
    "socketTimeout": 10000
}
```

Sadly there isn't much documentation, I took the information from here:
https://github.com/jhuckaby/Cronicle/issues/440#issuecomment-900962317

But it doesn't auth on my smtp server. Is there something else needed? I don't want to edit the config.json file in Cronicle. Ideally it would great to use CRONICLE_mail_options in docker-compose.yml and don't need the webinterface.

**Comment by mikeTWC1984** [comment]
Those config works a bit differently. You can only set 1 config value per key. If you have nested object (like mail_options), you need to specify each property separately. Key type is mainly used for display purposes. So you need do something like this:
![image](https://user-images.githubusercontent.com/31977106/184375467-3ecffc53-902c-4324-a458-aef0a2b7b5e2.png)
Then to verify actual current configs you can click on "config viewer" at the top right corner of admin tab.

**Comment by helmut72** [comment]
Thanks for clarify, works!
