### ISSUE TITLE
no custom html output when stderr used

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#38]
## Summary

My shell script writes custom html content to standard out. Normally this output is rendered in the log. If my script also writes output to standard error, then my custom html is not shown anymore.

## Steps to reproduce the problem
new event with shell plugin

script:
```
#!/bin/bash

echo "{\"html\":{\"title\":\"my title\",\"content\":\"<a href='http:/google.de' target='_blank'>link</a><br/>\"}}" 
echo This message goes to stdout
```
custom html content is shown
![image](https://user-images.githubusercontent.com/73586581/185336168-409142dc-5461-45e3-a8e7-97478834e655.png)

```
#!/bin/bash

echo "{\"html\":{\"title\":\"my title\",\"content\":\"<a href='http:/google.de' target='_blank'>link</a><br/>\"}}" 
echo This message goes to stdout
echo This message goes to stderr >&2
```
custom html content is not shown. I only see the error output.
![image](https://user-images.githubusercontent.com/73586581/185336247-0763903e-6cee-4432-99e9-bfcb503b16d4.png)

### Operating system and version?
RedHat 7

### Node.js version?
v14.20

### Cronicle software version?
Fork cronicle-edge 1.5.10.2

**Comment by mikeTWC1984** [comment]
OK, sync-ed all the recent fixes in 1.5.14 release
