### ISSUE TITLE
Workflow Plugin - "Error: failed to retrieve job state (check job logs)"

### ISSUE THREAD

**Issue by MrMeeb** [cronicle-edge/cronicle-edge#46]
cronicle-edge version: 1.16.0
Node version: v18.12.1
OS: Ubuntu 22.04.1 LTS

## Error Description

I am using Cronicle to manage automated backups of multiple servers/services. Each job is responsible for backing up a particular service or collection of services. These jobs are run one after another using a Workflow plugin that is scheduled for once a day. I went this route because I had previously used Cronicle's built-in job chaining feature, but it made it difficult to run a single job in the chain, or to reorder to the jobs. Workflows have been a good solution for me here.

The worker nodes are on multiple different machines/VMs, with the manager node existing in a cloud instance connected to the rest of the environment via a VPN. I'm not sure the following issue is network related, since Cronicle succefully determines the child job's status and that it finishes.

When running these Workflows, intermittently a Workflow will fail with `Error: failed to retreive job state (check job logs)`. Since I do not tolerate any job failures, this causes the whole Workflow to abort. The job it is referring to always completes succesfully. It does not happen consistently on the same job, or on the same Workflow, or on every run of a Workflow.

It's unclear which logs are meant by 'job logs' in the error, however I have checked `Cronicle.log`, `API.log`, `WebServer.log`, `Transaction.log` and `Error.log`. I cannot see anything that would suggest why this happened. The contents of `Error.log` are only that the Workflow failed. I also checked the log of the affected job in the WebUI, but it completed succesfully so there isn't much to take from it.

I'm looking for advice on where to look to troubleshoot this, since you know the inner workings of your Workflow plugin

## Cronicle config:

```
{
	"base_app_url": "http://mm-oci-1:3012",
	"email_from": "[REDACTED]",
	"smtp_hostname": "[REDACTED]",
	"smtp_port": 465,
	"mail_options": {
		"secure": true,
		"auth": { "user": "[REDACTED]", "pass": "[REDACTED]" },
		"connectionTimeout": 10000,
		"greetingTimeout": 10000,
		"socketTimeout": 10000
	},
	"secret_key": "[REDACTED]",
	"ad_domain": "corp.cronicle.com",
		
	"log_dir": "logs",
	"log_filename": "[component].log",
	"log_columns": ["hires_epoch", "date", "hostname", "pid", "component", "category", "code", "msg", "data"],
	"log_archive_path": "logs/archives/[yyyy]/[mm]/[dd]/[filename]-[yyyy]-[mm]-[dd].log.gz",
	"log_crashes": true,
	"pid_file": "logs/cronicled.pid",
	"copy_job_logs_to": "",
	"queue_dir": "queue",
	"debug_level": 10,
	"maintenance": "04:00",
	"list_row_max": 10000,
	"job_data_expire_days": 180,
	"child_kill_timeout": 10,
	"dead_job_timeout": 120,
	"manager_ping_freq": 20,
	"manager_ping_timeout": 60,
	"udp_broadcast_port": 3014,
	"scheduler_startup_grace": 10,
	"universal_web_hook": "",
	"track_manual_jobs": false,
	"max_jobs": 0,
	
	"server_comm_use_hostnames": true,
	"web_direct_connect": false,
	"web_socket_use_hostnames": true,
	
	"job_memory_max": 10737418240,
	"job_memory_sustain": 0,
	"job_cpu_max": 0,
	"job_cpu_sustain": 0,
	"job_log_max_size": 0,
	"job_env": {},
	
	"web_hook_text_templates": {
		"job_start": "🚀 *[event_title]* started on [hostname] <[job_details_url] | More details>",
		"job_complete": "✔️ *[event_title]* completed successfully on [hostname] <[job_details_url] | More details>",
		"job_warning": "⚠️ *[event_title]* completed with warning on [hostname]:\nWarning: _*[description]*_\n <[job_details_url] | More details>",
		"job_failure": "❌ *[event_title]* failed on [hostname]:\nError: _*[description]*_\n <[job_details_url] | More details>",
		"job_launch_failure": "💥 Failed to launch *[event_title]*:\n*[description]*\n<[edit_event_url] | More details>"
	  },
	
	"client": {
		"name": "Cronicle",
		"debug": 1,
		"default_password_type": "password",
		"privilege_list": [
			{ "id": "admin", "title": "Administrator" },
			{ "id": "create_events", "title": "Create Events" },
			{ "id": "edit_events", "title": "Edit Events" },
			{ "id": "delete_events", "title": "Delete Events" },
			{ "id": "run_events", "title": "Run Events" },
			{ "id": "abort_events", "title": "Abort Events" },
			{ "id": "state_update", "title": "Toggle Scheduler" }
		],
		"new_event_template": { 
			"enabled": 1, 
			"params": {}, 
			"timing": { "minutes": [0] },
			"max_children": 1,
			"timeout": 3600,
			"catch_up": 0,
			"queue_max": 1000
		}
	},

	"git": {
		"enabled": false,
		"auto": false,
		"user": "cronicle",
		"email": "croncile@cronicle.com",
		"remote": "origin",
		"branch": "master"
	},
	
	"Storage": {
		"engine": "Filesystem",
		"list_page_size": 50,
		"concurrency": 4,
		"log_event_types": { "get": 1, "put": 1, "head": 1, "delete": 1, "expire_set": 1 },
		
		"Filesystem": {
			"base_dir": "data",
			"key_namespaces": 1
		}
	},
	
	"WebServer": {
		"http_bind_address": "0.0.0.0",
		"http_port": 3012,
		"http_htdocs_dir": "htdocs",
		"http_max_upload_size": 104857600,
		"http_static_ttl": 3600,
		"http_static_index": "index.html",
		"http_server_signature": "Cronicle 1.0",
		"http_gzip_text": true,
		"http_timeout": 30,
		"http_regex_json": "(text|javascript|js|json)",
		"http_response_headers": {
			"Access-Control-Allow-Origin": "*"
		},
		
		"https": false,
		"https_port": 3013,
		"https_cert_file": "conf/ssl.crt",
		"https_key_file": "conf/ssl.key",
		"https_force": false,
		"https_timeout": 30,
		"https_header_detect": {
			"Front-End-Https": "^on$",
			"X-Url-Scheme": "^https$",
			"X-Forwarded-Protocol": "^https$",
			"X-Forwarded-Proto": "^https$",
			"X-Forwarded-Ssl": "^on$"
		}
	},
	
	"User": {
		"session_expire_days": 30,
		"max_failed_logins_per_hour": 5,
		"max_forgot_passwords_per_hour": 3,
		"free_accounts": false,
		"sort_global_users": true,
		"use_bcrypt": true,
		
		"email_templates": {
			"welcome_new_user": "conf/emails/welcome_new_user.txt",
			"changed_password": "conf/emails/changed_password.txt",
			"recover_password": "conf/emails/recover_password.txt"
		},
		
		"default_privileges": {
			"admin": 0,
			"create_events": 1,
			"edit_events": 1,
			"delete_events": 1,
			"run_events": 0,
			"abort_events": 0,
			"state_update": 0
		}
	}
	
}
```

## Example of a failing Workflow

![image](https://user-images.githubusercontent.com/16963756/215448953-e23d4608-0116-4348-91dc-d8d0cf461a27.png)

## Example of failed Workflow output

![image](https://user-images.githubusercontent.com/16963756/215722905-655d3914-784b-4407-9399-5db5c9a693b1.png)

Appreciate any input. Thanks!

**Comment by mikeTWC1984** [comment]
WF plugin checks list of actives jobs, and once queued job disappears from there, it starts hitting "get_job_details" api to get completed job status. If it can't retrieve this info within some time you will see this error.
This is  likely happens due to network issues (e.g. request timeout), although there could be other reasons (I have some thoughts, need to check)

Anyway, if need some quick fix you may try locate this snippet in bin/worklow.js
```js
						while (!jd.data) {
							try {
								await sleep(lag);
								jd = await getJson(baseUrl + '/api/app/get_job_details', { id: j })
							}
							catch {
								if (lag > 500) {
									console.log(" │ ⚠️ Failed to retreive data from get_job_details")
									jd = {
										data: {
											job: {
												code: 1,
												description: "failed to retreive job state (check job logs)",
												elapsed: 0
											}
										}
									}
									break

								}
								lag = lag*3								
							}
```

And replace "500" with some larger value (like 3000), and see if it helps. For better debugging you can also print error messages,
e.g. replace 
```js
catch {
```
with 
```js
catch (e) { console.log("ERROR: ", e.message) 
```
But in general I think we just need to treat such jobs as pending, and keep polling for result. I'll add this on the next release

**Comment by MrMeeb** [comment]
Hey, I made the changes suggested to extending the `lag` time, and adding the error message handling. Unfortunately this didn't improve the behaviour. What I did notice is that the WF plugin thinks the job completed immediately, whereas it actually took about 45 seconds to run:

![image](https://user-images.githubusercontent.com/16963756/216029404-5dc4a8fc-cde0-4ddf-aae1-2a3b49aef3cc.png)

![image](https://user-images.githubusercontent.com/16963756/216029485-e93cee1a-c418-49b7-81c3-799c7b54b661.png)

I assume this is behaviour that just results from WF being unable to find the run, as it states.

**Comment by mikeTWC1984** [comment]
That error comes from storage system, so that means there is some lag between removing job from active job list and logging job details in storage. 
Ok, so I'll update the logic a bit, to consider "finishing" jobs as active. Doesn't sounds to complicated, I'll post updated version here soon.

Out of curiosity:
What is your storage engine?
What is the volume of jobs you run daily?

**Comment by mikeTWC1984** [comment]
Ok, thanks for the clarification. While I never encountered that issue while running WF plugin, but I recall some jobs may stuck in "Finishing Up" state for quite a while (like few  or several seconds).  Maybe it's the same thing here. Are your script jobs using some exotic scripting language, or it's just bash?

**Comment by MrMeeb** [comment]
Nothing exotic, just bash. The jobs in Cronicle pull the actual scripts from a git repo, then run them from a temp dir on the worker machine.

**Comment by mikeTWC1984** [comment]
OK, here is the updated version of the WF plugin, which will be waiting for a job to finish as long as needed 
https://gist.github.com/mikeTWC1984/9afc415afa4f6e1969e86cd0f2a6d264
Please try and let me know.

**Comment by MrMeeb** [comment]
Thanks so much for the fast turnaround. I've installed the new WF plugin, please allow me a few days before confirming due to the slightly intermittent nature of the issue

**Comment by MrMeeb** [comment]
Changes made to the WF plugin have fixed the behaviour. Thanks for your assistance!
