### ISSUE TITLE
Installation guide without docker

### ISSUE THREAD

**Issue by chen-hui-long** [cronicle-edge/cronicle-edge#62]
Hi all, a big fan of cronicle and want to try out this fork as well. 
Understand that this fork is mainly to be installed using docker. However, is there any installation guide to install it without docker ? 
I would like to try out the features

**Comment by mikeTWC1984** [comment]
Sure. Basically you need to run bundle script, check notes from this release
https://github.com/cronicle-edge/cronicle-edge/releases/tag/v1.7.0
Long story short - just run this "./bunlde /path/to/folder

**Comment by chen-hui-long** [comment]
Thanks alot.

**Comment by edurguti** [comment]
hmmm.. I'm getting lots of dependency errors, will this run with node v16?
