### ISSUE TITLE
Stuck at empty page 

### ISSUE THREAD

**Issue by chen-hui-long** [cronicle-edge/cronicle-edge#69]
Hi, I have install cronicle-edge without docker, however it is stuck on empty page. 

![image](https://github.com/cronicle-edge/cronicle-edge/assets/41332714/6ce93e80-2858-4e9e-9f5b-86530a5413cf)

`[1698835505.7][2023-11-01 18:45:05][x-pc][494428][Cronicle][debug][3][No manager ping received within 60 seconds, choosing new manager][]
[1698835505.702][2023-11-01 18:45:05][x-pc][494428][Cronicle][debug][5][We are the top candidate for manager][]
[1698835505.702][2023-11-01 18:45:05][x-pc][494428][Cronicle][debug][3][We are becoming the manager server][]
[1698835505.713][2023-11-01 18:45:05][x-pc][494428][Cronicle][debug][4][Looking for leftover job JSON files: logs/jobs/*.json][]
[1698835505.714][2023-11-01 18:45:05][x-pc][494428][Cronicle][debug][4][Looking for leftover job logs: logs/jobs/*.log][]
[1698835560.705][2023-11-01 18:46:00][x-pc][494428][Cronicle][debug][4][Scheduler Minute Tick: Advancing time up to: 2023/11/01 18:46:00][]
[1698835620.709][2023-11-01 18:47:00][x-pc][494428][Cronicle][debug][4][Scheduler Minute Tick: Advancing time up to: 2023/11/01 18:47:00][]
[1698835680.714][2023-11-01 18:48:00][x-pc][494428][Cronicle][debug][4][Scheduler Minute Tick: Advancing time up to: 2023/11/01 18:48:00][]`

Didn't see anything weird with the logs as well

**Comment by mikeTWC1984** [comment]
Sounds like you trying to start cronicle from repo directory. If you just ran "./bundle" the actual bundle will be created under ./dist folder. So you need to run ./dist/bin/manager

**Comment by chen-hui-long** [comment]
@mikeTWC1984 hi, I tried ./dist/bin/manager, however, it still shows an empty page.

**Comment by chen-hui-long** [comment]
In the console, this is the error message
```
Uncaught ReferenceError: app is not defined
    <anonymous> http://localhost:8111/api/app/config:1
[config:1:1](http://localhost:8111/api/app/config)
```

**Comment by mikeTWC1984** [comment]
so it has some issue loading combo.js. Check  if ./dist/htdocs/ folder exist. Also in dev tool check network tab, it should indicate which js files failed to load.

**Comment by chen-hui-long** [comment]
[dist.zip](https://github.com/cronicle-edge/cronicle-edge/files/13408098/dist.zip)

Hey mike, thanks for you help. I have uploaded the dist. I have retried and did not change the port this time round.

Steps that I did:
1. Clone from github 
2. ./bundle /home/huilong/cronicle-edge/dist
3.  cd /home/huilong/cronicle-edge/dist
4. npm install ./bin 
5. copied lib folder from git clone folder to /home/huilong/cronicle-edge/dist -> There isn't a `lib` created folder from step 2 
7. node bin/storage-cli.js setup
8. ./bin/control.sh start 

Thanks alot, appreciate it

**Comment by mikeTWC1984** [comment]
OK, so you are doing something strange. After you run bundle, it should generate dist folder. dist/bin should contain cronicle.js (and you don't have it) which is main app. You should not copy over lib (cronicle.js is compilation of it). Moreover, all the plugins should be "bundled" too, they should be like 200-500KB of size. Step 3 from above is not necessary.
Looks like bundling step failing. Can you clone the repo again, and just run ./bundle ? Paste here the output of this command.

**Comment by chen-hui-long** [comment]
`./bundle 
------------------------------------------------------
 Installing cronicle bundle into /home/huilong/cronicle-edge/dist
------------------------------------------------------

 ---- Installing esbuild [09:07:43]

changed 2 packages in 5s

 ---- Installing npm packages [09:07:49]
npm WARN deprecated @aws-sdk/hash-stream-node@3.374.0: This package has moved to @smithy/hash-stream-node

added 326 packages, and audited 327 packages in 7s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 ---- Building frontend [09:07:56]
./bundle: line 203: esbuild: command not found
./bundle: line 214: esbuild: command not found
./bundle: line 233: esbuild: command not found

 ---- Bundle storage-cli and event plugins [09:07:56]
./bundle: line 239: esbuild: command not found
./bundle: line 243: esbuild: command not found
./bundle: line 244: esbuild: command not found
./bundle: line 245: esbuild: command not found
./bundle: line 246: esbuild: command not found
./bundle: line 247: esbuild: command not found
./bundle: line 248: esbuild: command not found

 ---- Building Storage Engines [09:07:56]
      - bundling FS Engine
./bundle: line 262: esbuild: command not found

 ---- Bundling cronicle.js [09:07:56]
./bundle: line 306: esbuild: command not found

 ---- Applyig some patches [09:07:56]
./bundle: line 310: esbuild: command not found

 ---- Setting up initial configs [09:07:56]

 ---- Setting up npm package in dist [09:07:56]

 ---- Final cleanup [09:07:57]

---------------------------------------------------------------------------------------------------------------------------------------

Bundle is ready: /home/huilong/cronicle-edge/dist

Before you begin:
 - Configure you storage engine setting in conf/config.json || conf/storage.json || CRONICLE_storage_config=/path/to/custom/storage.json
 - Set you Secret key in conf/config.json || conf/secret_key file || CRONICLE_secret_key_file || CRONICLE_secret_key env variables

To setup cronicle storage (on the first run):
 node dist/bin/storage-cli.js setup

Start as manager in foreground:
 node dist/bin/cronicle.js --echo --foreground --manager --color

Or use dist/bin/manager script to setup storage + start cronicle in single manager mode

To reinstall/upgrade run:  ./bundle.sh dist -f 
Please back up /home/huilong/cronicle-edge/dist first for prod deployments

To setup as systemd service (! make sure node version for sudo user is 16 or higher):
 cd /home/huilong/cronicle-edge/dist
 npm i pixl-boot
 sudo node node_modules/pixl-boot/cli.js install
 ### systemctl status croniclex

To remove service:
 sudo node node_modules/pixl-boot/cli.js uninstall

---------------------------------------------------------------------------------------------------------------------------------------
`

This is the output

**Comment by mikeTWC1984** [comment]
OK, so obviously there is an issue with installing esbuild. Typically after you run 
```bash
npm i esbuild -g
```
esbuild should be available as cli tool (like many other node tools). Check where is your node's bin folder, it's probably not in your PATH variable. Or try too find "esbuild" file on your machine, then add this folder to path.
What is your OS btw?

**Comment by chen-hui-long** [comment]
Hi Mike, 

Thanks for the help, manage to resolve the issue. I am using `Ubuntu 20.04.5 LTS` btw,

In case anyone face similar issue in the future. 
This are the steps that i tried. 
1. Adding esbuild to path -> in my case, esbuild is located at ./node_modules/.bin for my pc -> this does **not** solve the issue, but worth a try. 
2. `npm install esbuild` command in the repo folder -> This manage to solve the issue
