### ISSUE TITLE
SQL.js - Don't use quotes around table names or column names for Oracle database 

### ISSUE THREAD

**Issue by kranskydog** [cronicle-edge/cronicle-edge#73]
Oracle databases by default convert object names,columns, and all other identifiers to upper case. It is frowned upon to have lower case identifiers and *strongly* discouraged

SQL.js has

        if (this.client === 'oracledb') { // need to pass large blob via variable to avoid "too long" error
            this.mergeStmt = `
            DECLARE
            k VARCHAR(256);
            b BLOB;
           BEGIN 
               k := ?;
               b := ?;
               MERGE INTO "${this.tableName}" T
               USING (SELECT k AS K FROM DUAL) S
               ON (s.K = t.K)
               WHEN MATCHED THEN UPDATE SET t.V = b, t."updated" = CURRENT_TIMESTAMP
               WHEN NOT MATCHED THEN INSERT (K, V) VALUES (s.K, b );
           END;     
            `
        }

The quotes around '${this.tableName}' and 'updated' will be atypical in any Oracle database, and should not be used.

Knex by default quotes identifiers, but this behaviour can be modified by adding:

"wrapIdentifier": (value, origImpl, queryContext) => origImpl(value.toUpperCase())

I.e

async setup(callback) {
        // setup SQL connection
        const self = this;
        const sql_config = this.config.get();

        this.client = sql_config.client
        if (this.client === 'oracledb') {
              sql_config.wrapIdentifier = (value, origImpl, queryContext) => origImpl(value.toUpperCase())
        }
        this.db = knex(sql_config)

so if cronicle creates the table, it will be created correctly with uppercase identifiers.

See https://github.com/knex/knex/issues/632

**Comment by kranskydog** [comment]
So, this is weird.

I am precreating the table to avoid any issues there.

Without 'wrapIdentifier', but removing the quotes around the identifiers in the 'merge' statement for oracledb, running 'control.sh setup' does the set up correctly, with all the expected initial entries for things like server_groups and plugins

but *with* 'wrapIdentifier', the setup completes but I only get the last entry in things like  server_groups and plugins

**Comment by kranskydog** [comment]
similarly - with wrapIdentifier, 'control.sh export ' can't find anything, but without wrapIdentifier, the export works

**Comment by kranskydog** [comment]
Finally worked it out - once you introduce wrapIdentifier, it affects the column aliases (and consequently the expected return values)
simplest solution was to add knex-stringcase to the mix to modify the case both to and from the database to expected values.

If and when i get around to it I might do a pull request

**Comment by mikeTWC1984** [comment]
Hm, yeah, it looks like that was the reason I added quotes to those Oracle statements. I recall I had a hard time with table/column name casing (for different db types), likely because of this quoting (which I didn't realize Knex was doing). 
OK, publish your findings or submit PR.

**Comment by kranskydog** [comment]
So, I've only made the change for the 'oracledb' case, because I don't know enough about the other SQL engines to know what the implications are for defaults knex-stringcase uses, and what the appropriate settings might be. It is also possible they could be set in the config file, but I haven't tested that.

--- SQL.js.orig 2023-11-24 09:46:14.152152747 +1100
+++ SQL.js.new  2023-11-24 09:43:47.674553089 +1100
@@ -12,7 +12,8 @@
 
 
 const Component = require("pixl-server/component");
-const { knex, Knex } = require('knex')
+const { knex, Knex } = require('knex');
+const knexStringcase = require('knex-stringcase');
 const { Readable } = require('stream');
 
 module.exports = class SQLEngine extends Component {
@@ -64,7 +65,16 @@
         const self = this;
         const sql_config = this.config.get();
 
-        this.db = knex(sql_config)
+        this.client = sql_config.client
+        if (this.client === 'oracledb') {
+              sql_config.stringcase = 'uppercase';
+              sql_config.appStringcase = 'lowercase';
+              const knex_config = knexStringcase(sql_config)
+              this.db = knex(knex_config)
+        }
+        else {
+              this.db = knex(sql_config)
+        }
 
         this.db.client.pool.on('createSuccess', () => {
             self.logDebug(3, "SQL connected successfully")           
@@ -72,7 +82,6 @@
 
         this.tableName = sql_config.table || 'cronicle'
 
-        this.client = sql_config.client
         
         if (this.client === 'mssql') {
             this.getBlobSizeFn = 'len(V)'
@@ -93,10 +102,10 @@
            BEGIN 
                k := ?;
                b := ?;
-               MERGE INTO "${this.tableName}" T
+               MERGE INTO ${this.tableName} T
                USING (SELECT k AS K FROM DUAL) S
                ON (s.K = t.K)
-               WHEN MATCHED THEN UPDATE SET t.V = b, t."updated" = CURRENT_TIMESTAMP
+               WHEN MATCHED THEN UPDATE SET t.V = b, t.updated = CURRENT_TIMESTAMP
                WHEN NOT MATCHED THEN INSERT (K, V) VALUES (s.K, b );
            END;     
             `
@@ -217,7 +226,7 @@
         this.logDebug(9, "Fetching SQL Object: " + key);
 
         try {
-            let data = (await this.db(this.tableName).where('K', key).select(["K as key", 'V as value']))[0] // expected {key: key, value: value}
+            let data = (await this.db(this.tableName).where('K', key).select(['K as key', 'V as value']))[0] // expected {key: key, value: value}
             let result = (data || {}).value
             if (result) {
                 if (self.storage.isBinaryKey(key)) {

**Comment by kranskydog** [comment]
So, I've only made the change for the 'oracledb' case, because I don't know enough about the other SQL engines to know what the implications are for defaults knex-stringcase uses, and what the appropriate settings might be. It is also possible they could be set in the config file, but I haven't tested that.

`--- SQL.js.orig 2023-11-24 09:46:14.152152747 +1100
+++ SQL.js.new  2023-11-24 09:43:47.674553089 +1100
@@ -12,7 +12,8 @@
 
 
 const Component = require("pixl-server/component");
-const { knex, Knex } = require('knex')
+const { knex, Knex } = require('knex');
+const knexStringcase = require('knex-stringcase');
 const { Readable } = require('stream');
 
 module.exports = class SQLEngine extends Component {
@@ -64,7 +65,16 @@
         const self = this;
         const sql_config = this.config.get();
 
-        this.db = knex(sql_config)
+        this.client = sql_config.client
+        if (this.client === 'oracledb') {
+              sql_config.stringcase = 'uppercase';
+              sql_config.appStringcase = 'lowercase';
+              const knex_config = knexStringcase(sql_config)
+              this.db = knex(knex_config)
+        }
+        else {
+              this.db = knex(sql_config)
+        }
 
         this.db.client.pool.on('createSuccess', () => {
             self.logDebug(3, "SQL connected successfully")           
@@ -72,7 +82,6 @@
 
         this.tableName = sql_config.table || 'cronicle'
 
-        this.client = sql_config.client
         
         if (this.client === 'mssql') {
             this.getBlobSizeFn = 'len(V)'
@@ -93,10 +102,10 @@
            BEGIN 
                k := ?;
                b := ?;
-               MERGE INTO "${this.tableName}" T
+               MERGE INTO ${this.tableName} T
                USING (SELECT k AS K FROM DUAL) S
                ON (s.K = t.K)
-               WHEN MATCHED THEN UPDATE SET t.V = b, t."updated" = CURRENT_TIMESTAMP
+               WHEN MATCHED THEN UPDATE SET t.V = b, t.updated = CURRENT_TIMESTAMP
                WHEN NOT MATCHED THEN INSERT (K, V) VALUES (s.K, b );
            END;     
             `
@@ -217,7 +226,7 @@
         this.logDebug(9, "Fetching SQL Object: " + key);
 
         try {
-            let data = (await this.db(this.tableName).where('K', key).select(["K as key", 'V as value']))[0] // expected {key: key, value: value}
+            let data = (await this.db(this.tableName).where('K', key).select(['K as key', 'V as value']))[0] // expected {key: key, value: value}
             let result = (data || {}).value
             if (result) {
                 if (self.storage.isBinaryKey(key)) {
`

**Comment by kranskydog** [comment]
So, I've only made the change for the 'oracledb' case, because I don't know enough about the other SQL engines to know what the implications are for defaults knex-stringcase uses, and what the appropriate settings might be. It is also possible they could be set in the config file, but I haven't tested that.

```diff
--- SQL.js.orig 2023-11-24 09:46:14.152152747 +1100
+++ SQL.js.new  2023-11-24 09:43:47.674553089 +1100
@@ -12,7 +12,8 @@
 
 
 const Component = require("pixl-server/component");
-const { knex, Knex } = require('knex')
+const { knex, Knex } = require('knex');
+const knexStringcase = require('knex-stringcase');
 const { Readable } = require('stream');
 
 module.exports = class SQLEngine extends Component {
@@ -64,7 +65,16 @@
         const self = this;
         const sql_config = this.config.get();
 
-        this.db = knex(sql_config)
+        this.client = sql_config.client
+        if (this.client === 'oracledb') {
+              sql_config.stringcase = 'uppercase';
+              sql_config.appStringcase = 'lowercase';
+              const knex_config = knexStringcase(sql_config)
+              this.db = knex(knex_config)
+        }
+        else {
+              this.db = knex(sql_config)
+        }
 
         this.db.client.pool.on('createSuccess', () => {
             self.logDebug(3, "SQL connected successfully")           
@@ -72,7 +82,6 @@
 
         this.tableName = sql_config.table || 'cronicle'
 
-        this.client = sql_config.client
         
         if (this.client === 'mssql') {
             this.getBlobSizeFn = 'len(V)'
@@ -93,10 +102,10 @@
            BEGIN 
                k := ?;
                b := ?;
-               MERGE INTO "${this.tableName}" T
+               MERGE INTO ${this.tableName} T
                USING (SELECT k AS K FROM DUAL) S
                ON (s.K = t.K)
-               WHEN MATCHED THEN UPDATE SET t.V = b, t."updated" = CURRENT_TIMESTAMP
+               WHEN MATCHED THEN UPDATE SET t.V = b, t.updated = CURRENT_TIMESTAMP
                WHEN NOT MATCHED THEN INSERT (K, V) VALUES (s.K, b );
            END;     
             `
@@ -217,7 +226,7 @@
         this.logDebug(9, "Fetching SQL Object: " + key);
 
         try {
-            let data = (await this.db(this.tableName).where('K', key).select(["K as key", 'V as value']))[0] // expected {key: key, value: value}
+            let data = (await this.db(this.tableName).where('K', key).select(['K as key', 'V as value']))[0] // expected {key: key, value: value}
             let result = (data || {}).value
             if (result) {
                 if (self.storage.isBinaryKey(key)) {
```

**Comment by mikeTWC1984** [comment]
Sorry, it took forever, but I finally updated engine itself to enforce upper case for oracle driver (without using extra libraries). Interestingly, the latest oracledb driver doesn't need instantclient anymore (it's pure js).  I added a separate flag to bundler to install just oracle driver with SQL engine: ``` ./bundle --oracle```
