### ISSUE TITLE
Option to hide event flow

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#80]
Hi Mike,

I would find it helpful if you could switch off the event flow display under home using a config switch. The large number of jobs (approx. 63,000 jobs per day) that run on our cluster means that the home page jumps back and forth a lot when the display is updated again and again after another job is completed.

what do you think of this?

Daniel

**Comment by mikeTWC1984** [comment]
I added it on 1.8.0. Just realized I haven't mention it on release notes, so just FYI. You can choose "hide" option in the drop down "Last N" menu

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Mike,

I already saw the new option in your commits. Will upgrade my cluster in the next days. 💪

Thank you a lot for your fast implementation.
Daniel
