### ISSUE TITLE
files in ./data/logs ./data/jobs ./data/global are writing the whole command line with password in clear text to disk

### ISSUE THREAD

**Issue by mamema** [cronicle-edge/cronicle-edge#82]
more or less the topic in question.
as cronicle is a cron master beast, of course passwords are needed to connect to services.
saving rhose in clear text is not a good idea

it makes chronicle-edge to a password harbour which makes every password safety tool useless

**Comment by mikeTWC1984** [comment]
Can you give me an example of event/command you run?  
If you need to use sensitive data like PWD, you can create entry in secret section. It will be mounted as env variable and it won't be logged, unless you echo it. 
I'm also going plugin/job specific secrets.

**Comment by mamema** [comment]
oh there are a pletora of examples. i'm mainly using the script solution.
there someone can find
ssh -p $ssh_port -i /root/.ssh/id_rsa $scp_server 'openssl pkcs12 -password pass:Password -export -out /conf/acme/cert_pass.pfx -inkey /conf/acme/cert_wildcard.key -in /conf/acme/cert_wildcard.crt -certfile /conf/acme/cert_wildcard.ca'

i'm not quite sure if i understand you correct? Are you talking about your own secret implementation, i've used it above for $scp_server, or are you talking about docker secrets?

The Password in the line above is in cleartext though, so do you mean shifting this to your secrets area?

Is this then the solution that nothing gets written into logs, jobs, global?

**Comment by mikeTWC1984** [comment]
Yes, it's internal implementation, not docker
Go to admin tab, then secrets. You will see editor, which you can add env variables in .env style
To encrypt then click "encrypt" button. 
![image](https://github.com/cronicle-edge/cronicle-edge/assets/31977106/6ca47fc8-6876-4cf6-b571-4261b4e08e57)

Then in your shell script you can use $MYPASSWORD variable.

**Comment by mikeTWC1984** [comment]
for ssh stuff there is a separate plugin, although it won't work well with those secrets. I'm going to release a new version of ssh plugin to fix that soon

**Comment by mamema** [comment]
this would be great, because as you can see above i'm using scp. I cannot see where in the ssh plugin this is....perhaps i'm using it wrong....

**Comment by mamema** [comment]
so, i've followed your advice, it's working, but for reference: the encryption encrypts the event data, but not job data and log data, so to remove remaining cleartext informatation the contents of ./data/jobs and ./data/logs need to be deleted

**Comment by mikeTWC1984** [comment]
Well, the stuff that comes from secrets is mounted as env variable to the child process and not stored on disk at any time I'm not evaluating it
Say if you script look like this 
"openssl pkcs12 -password pass:$MYPASSWORD"
It will be logged the same way. It won't look as "openssl pkcs12 -password pass:P@ssword".  Or am I missing something?

**Comment by mamema** [comment]
no you're right. So this is sloved. Thank you!
