### ISSUE TITLE
cannot reset password / request new password

### ISSUE THREAD

**Issue by mamema** [cronicle-edge/cronicle-edge#86]
out of the blue cronicle-edge doesn't accept my login password.

So i tried to recover it.
Found recover information here:
https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#recover-admin-access

/opt/cronicle/bin/control.sh admin USERNAME PASSWORD

but for this, cronicle-edge server must be stopped.
If i do this, then the docker container stops also. This is a dead end.

So i've tried to go the route with "forget password" this wasn't working, as it wasn't configured by me. No smtp server and so on.
But there was a file created in the folder "password_recovery".
Within this file there was a key defined.....

then i found a email template txt for email password recovery and i build the recovery url by myself.

It was looking like this:

http://ip:port/#Login?u=admin&h=key_from_file

then i was redirected to the password reset page.
But when i enter a password there and press the "Reset password" button - Nothing happens.

So i'm locked out and don't know how to proceed

using 1.8.0 latest docker image.....

**Comment by mikeTWC1984** [comment]
If you just have admin user,  you can open this file
data/users/34/68/bc/3468bc0c4e5f6aa06c7aee62212ac18f.json
This is how it looks by default. If you want reset it to default (admin/admin), use the same password (hash) and salt property values
```json
{"username":"admin","password":"$2a$10$VAF.FNvz1JqhCAB5rCh9GOa965eYWH3fcgWIuQFAmsZnnVS/.ye1y","full_name":"Administrator","email":"admin@cronicle.com","active":1,"modified":1710374852,"created":1710010228,"salt":"salty","privileges":{"admin":1},"ext_auth":false,"fl_date_code":475104,"fl_count":1}
```

Do you think this might be related to version upgrade to 1.8.0?

**Comment by mamema** [comment]
i'm not sure, as i wasn't using the solution for a period of time.
i found a solution by myself.
i've recreated the container and changed the entrypoint from starting cronicle-edge to /bin/bash
then the container was running without the cronicle-edge service and i was able to use the recovery solution
/opt/cronicle/bin/control.sh admin USERNAME PASSWORD

i have now again access. the proposed solution from you is also a good one. 
i'm observating the container for a few days, if this is happening again.
the solution was working fine on docker swarm until this issue occured

**Comment by mikeTWC1984** [comment]
OK, good. I thi9nk one of the scenarios when password can change - it's browser auto-completion. I had such issue with secrets section on firefox. It keep replacing value in there to the one it stored. I had to create a dummy form input to fix it.

**Comment by mamema** [comment]
even though issue is closed, i want to mention, that email sending for forgotten passwords is working, but then when you have to enter the new password in the gui, the expected "done" message didn't show up, it just stays on the change password page.

**Comment by TBI-NS** [comment]
> If you just have admin user, you can open this file data/users/34/68/bc/3468bc0c4e5f6aa06c7aee62212ac18f.json This is how it looks by default. If you want reset it to default (admin/admin), use the same password (hash) and salt property values
> 
> {"username":"admin","password":"$2a$10$VAF.FNvz1JqhCAB5rCh9GOa965eYWH3fcgWIuQFAmsZnnVS/.ye1y","full_name":"Administrator","email":"admin@cronicle.com","active":1,"modified":1710374852,"created":1710010228,"salt":"salty","privileges":{"admin":1},"ext_auth":false,"fl_date_code":475104,"fl_count":1}
> Do you think this might be related to version upgrade to 1.8.0?

Thank you so much !
