### ISSUE TITLE
Future of cronicle-edge

### ISSUE THREAD

**Issue by mcfetz** [cronicle-edge/cronicle-edge#90]
Hi Mike,

I'm just wondering what will happen to Cronicle-Edge when Joseph's new Cronicle V2 aka Orchestra comes out? Will your fork live on as an independent version or will you stop further development?

Daniel

**Comment by mikeTWC1984** [comment]
Likely will continue. I'd wait till v2 is released first. I think it was announced over 2 years ago,  it might take another 2 to release it :)

**Comment by mcfetz** [comment]
Nice to read and thank you for your work. 💪
