### ISSUE TITLE
docker plugin missing

### ISSUE THREAD

**Issue by mamema** [cronicle-edge/cronicle-edge#91]
i've just recognized that my docker installed (from your image) container is missing the docker plugin

i have:
HTTP Request
Shell Script
SSH
Test Plugin
Workflow

but no docker plugin as shown in your screenshots.

on the release page i found this:
"Please note - on existing cronicle setups both new plugins need to be set manually."

but it's not clear what needs to be done.

any hint?

**Comment by mikeTWC1984** [comment]
Yes, plugin data is loaded on initial setup, and if a new plugin added after that, you need to recreate it manually.  You can run a temp instance of the latest cronicle, and recreate this plugin in you current setup using same parameters
```bash
docker run -it -p 3012:3012 cronicle/edge:v1.8.1 manager
```
It's a known quirk, I'll add some option to do json import or something like that later
